
<a class="btn btn-sm btn-default" href="<?php echo $this->url('Shop:Admin:AttributeValue@addAction'); ?>"><i class="glyphicon glyphicon-tag"></i> <?php $this->show('Add attribute'); ?></a>
<a class="btn btn-sm btn-primary" href="<?php echo $this->url('Shop:Admin:AttributeGroup@addAction'); ?>"><i class="glyphicon glyphicon-book"></i> <?php $this->show('Add group'); ?></a>

<div class="row">
    <div class="col-lg-6">
        <h4><i class="glyphicon glyphicon-tags"></i> <?php $this->show('Values'); ?></h4>

        <table class="table table-bordered">
            <thead>
                <tr>
                    <td class="text-center">#</td>
                    <td class="text-center"><?php $this->show('Attribute'); ?></td>
                    <td class="text-center"><?php $this->show('Actions'); ?></td>
                </tr>
            </thead>
            
            <tbody>
                <?php foreach ($values as $value): ?>
                <tr>
                    <td class="text-center text-muted"><?php echo $value->getId(); ?></td>
                    <td class="text-center"><?php echo $value->getName(); ?></td>
                    <td class="text-center">
                        <a data-toggle="tooltip" data-placement="left" data-original-title="<?php $this->show('Edit this attribute'); ?>" data-button="edit" href="<?php echo $this->url('Shop:Admin:AttributeValue@editAction', $value->getId()); ?>"><i class="glyphicon glyphicon-pencil"></i></a>
                        <a data-toggle="tooltip" data-placement="left" data-original-title="<?php $this->show('Remove this attribute'); ?>" data-button="delete" data-url="<?php echo $this->url('Shop:Admin:AttributeValue@deleteAction', $value->getId()); ?>" href="#"><i class="glyphicon glyphicon-remove"></i></a>
                    </td>
                </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    </div>

    <div class="col-lg-6">
        <h4><i class="glyphicon glyphicon-book"></i> <?php $this->show('Groups'); ?></h4>
        <table class="table table-bordered">
            <thead>
                <tr>
                    <td class="text-center">#</td>
                    <td class="text-center"><?php $this->show('Group'); ?></td>
                    <td class="text-center"><?php $this->show('Actions'); ?></td>
                </tr>
            </thead>

            <tbody>
                <?php foreach ($groups as $group): ?>
                <tr class="<?php echo $groupId == $group->getId() ? 'info' : ''; ?>">
                    <td class="text-center text-muted"><?php echo $group->getId(); ?></td>
                    <td class="text-center">
                        <a href="<?php echo $this->url('Shop:Admin:Attributes@groupAction', $group->getId()); ?>"><?php echo $group->getName(); ?></a>
                    </td>
                    <td class="text-center">
                        <a data-toggle="tooltip" data-placement="left" data-original-title="<?php $this->show('Edit this group'); ?>" data-button="edit" href="<?php echo $this->url('Shop:Admin:AttributeGroup@editAction', $group->getId()); ?>"><i class="glyphicon glyphicon-pencil"></i></a>
                        <a data-toggle="tooltip" data-placement="left" data-original-title="<?php $this->show('Remove this group'); ?>" data-button="delete" data-url="<?php echo $this->url('Shop:Admin:AttributeGroup@deleteAction', $group->getId()); ?>" href="#"><i class="glyphicon glyphicon-remove"></i></a>
                    </td>
                </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    </div>
</div>

