<?php

use Krystal\Widget\GridView\GridViewWidget;
use Krystal\Form\Element;
use Cms\View\Icon;

defined('KRYSTAL') or die;

?>

<div class="row">
    <div class="col-lg-6 mb-4">
        <div class="card">
            <div class="card-header">
                <h3 class="card-title m-0">
                    <i class="bi bi-patch-check"></i> <?php $this->show('Brands'); ?> <small class="text-muted">(<?= count($brands); ?>)</small>
                </h3>
            </div>
            <div class="card-body">
                <?= $this->widget(new GridViewWidget($brands, [
                    'tableClass' => 'table table-hover table-bordered table-striped',
                    'rowAttributes' => [
                        'class' => function($row) use ($brand){
                            return $row['id'] == $brand->getId() ? 'table-info' : null;
                        }
                    ],

                    'columns' => [
                        [
                            'column' => 'id',
                            'label' => '#'
                        ],
                        [
                            'column' => 'name',
                        ],
                        [
                            'column' => 'order'
                        ]
                    ],

                    'actions' => [
                        function($row){
                            return Icon::edit(
                                $this->url('Shop:Admin:Brand@editAction', $row['id']),
                                $this->translate('Edit this brand')
                            );
                        },

                        function($row){
                            return Icon::remove(
                                $this->url('Shop:Admin:Brand@deleteAction', $row['id']),
                                $this->translate('Remove this brand')
                            );
                        }
                    ]
                ])); ?>
            </div>
        </div>
    </div>

    <div class="col-lg-6">
        <div class="card">
            <div class="card-header">
                <h4 class="card-title m-0"><i class="bi bi-pencil"></i> <?php $this->show($title); ?></h4>
            </div>

            <div class="card-body">
                <form data-group="brand" autocomplete="off">
                    <?= Element::hidden('brand[id]', $brand->getId()); ?>

                    <div class="form-group mb-3">
                        <label class="form-label"><?php $this->show('Name'); ?></label>
                        <div class="input-group">
                            <?= Element::text('brand[name]', $brand->getName(), ['class' => 'form-control', 'placeholder' => $this->translate('Name')]); ?>
                            <div class="input-group-append">
                                <span class="input-group-text"><i class="bi bi-pencil"></i></span>
                            </div>
                        </div>
                    </div>

                    <div class="form-group mb-3">
                        <label class="form-label"><?php $this->show('Order'); ?></label>
                        <div class="input-group">
                            <?= Element::text('brand[order]', $brand->getOrder(), ['class' => 'form-control', 'placeholder' => $this->translate('Sorting order')]); ?>
                            <div class="input-group-append">
                                <span class="input-group-text"><i class="bi bi-pencil"></i></span>
                            </div>
                        </div>
                    </div>

                    <?php $this->loadPartial('actions', [
                        'new' => $new,
                        'add' => 'Shop:Admin:Brand@addAction',
                        'edit' => 'Shop:Admin:Brand@editAction',
                        'save' => 'Shop:Admin:Brand@saveAction',
                        'cancel' => 'Shop:Admin:Browser@indexAction'
                    ]); ?>
                </form>
            </div>
        </div>
    </div>
</div>