<?php

use Krystal\Form\Element;
use Krystal\Widget\GridView\GridViewWidget;
use Cms\View\Icon;

defined('KRYSTAL') or die;
$categoryId = $filter->get('category_id') ? $filter->get('category_id') : $categoryId;

?>

<form novalidate autocomplete="off">
    <div class="btn-toolbar">
        <div class="btn-group mr-2">
            <div class="dropdown">
              <button type="button" class="btn btn-primary  dropdown-toggle" data-toggle="dropdown">
                <i class="glyphicon glyphicon-list"></i> <?php $this->show('Menu'); ?><span><?php if ($newOrdersCount > 0): ?> (<?php echo $newOrdersCount; ?>) <?php endif; ?> </span>
              </button>

              <div class="dropdown-menu">
                 <?php if (isset($categoryId)): ?>
                 <a class="dropdown-item" href="<?php echo $this->url('Shop:Admin:Browser@indexAction'); ?>"><i class="glyphicon glyphicon-home"></i> <?php $this->show('Go home'); ?></a>
                 <li class="divider">
                 <?php endif; ?>

                 <a class="dropdown-item" href="<?php echo $this->url('Shop:Admin:Product@addAction'); ?>"><i class="glyphicon glyphicon-shopping-cart"></i> <?php $this->show('Add product'); ?></a>
                 <a class="dropdown-item" href="<?php echo $this->url('Shop:Admin:Category@addAction'); ?>"><i class="glyphicon glyphicon-folder-open"></i> <?php $this->show('Add category'); ?></a>
                 <a class="dropdown-item" href="<?php echo $this->url('Shop:Admin:Config@indexAction'); ?>"><i class="glyphicon glyphicon-th-large"></i> <?php $this->show('Configuration'); ?></a>
                 <a class="dropdown-item" href="<?php echo $this->url('Shop:Admin:Order@indexAction'); ?>"><i class="glyphicon glyphicon-user"></i> <?php $this->show('Orders'); ?><?php if ($newOrdersCount > 0): ?><span> (<?php echo $newOrdersCount; ?>) </span><?php endif; ?></a>
                 <a class="dropdown-item" href="#" data-button="statistic" data-url="<?php echo $this->url('Shop:Admin:Statistic@indexAction'); ?>"><i class="glyphicon glyphicon-calendar"></i> <?php $this->show('Statistic'); ?></a>
                 <div class="dropdown-header"><?php $this->show('Configurable parameters'); ?></div>
                 <a class="dropdown-item" href="<?php echo $this->url('Shop:Admin:Brand@indexAction'); ?>"><i class="glyphicon glyphicon-certificate"></i> <?php $this->show('Brands'); ?></a>
                 <a class="dropdown-item" href="<?php echo $this->url('Shop:Admin:SpecificationItem@indexAction', null); ?>"><i class="glyphicon glyphicon-edit"></i> <?php $this->show('Specifications'); ?></a>
                 <a class="dropdown-item" href="<?php echo $this->url('Shop:Admin:Attributes@indexAction'); ?>"><i class="glyphicon glyphicon-th-list"></i> <?php $this->show('Attributes'); ?></a>
                 <a class="dropdown-item" href="<?php echo $this->url('Shop:Admin:DeliveryType@indexAction'); ?>"><i class="glyphicon glyphicon-list-alt"></i> <?php $this->show('Delivery types'); ?></a>
                 <a class="dropdown-item" href="<?php echo $this->url('Shop:Admin:Coupon@indexAction'); ?>"><i class="glyphicon glyphicon-link"></i> <?php $this->show('Discount coupons'); ?></a>
                 <a class="dropdown-item" href="<?php echo $this->url('Shop:Admin:Currency@indexAction'); ?>"><i class="glyphicon glyphicon-header"></i> <?php $this->show('Currencies'); ?></a>
                 <a class="dropdown-item" href="<?php echo $this->url('Shop:Admin:OrderStatus@indexAction'); ?>"><i class="glyphicon glyphicon-header"></i> <?php $this->show('Order statuses'); ?></a>
                 <div class="dropdown-divider"></div>
                 <div class="dropdown-header"><?php $this->show('Actions'); ?></div>
                 
                 <?php if (!empty($products)):?>
                 <a class="dropdown-item" href="#" data-button="save-changes" data-url="<?php echo $this->url('Shop:Admin:Product@tweakAction'); ?>"><i class="glyphicon glyphicon-floppy-save"></i> <?php $this->show('Save changes');?></a>
                 <a class="dropdown-item" href="#" data-button="remove-selected" data-url="<?php echo $this->url('Shop:Admin:Product@deleteAction', null); ?>"><i class="glyphicon glyphicon-remove"></i> <?php $this->show('Remove selected'); ?></a>
                 
                 <?php else: ?>
                 <li class="disabled"><a class="dropdown-item"><i class="glyphicon glyphicon-floppy-save"></i> <?php $this->show('Save changes');?></a>
                 <li class="disabled"><a class="dropdown-item"><i class="glyphicon glyphicon-remove"></i> <?php $this->show('Remove selected'); ?></a>
                 
                 <?php endif; ?>
              </div>
            </div>
        </div>

        <?php if (!empty($products)): ?>
        <div class="btn-group mr-2">
            <button type="submit" class="btn btn-primary"><i class="fas fa-search"></i> <?php $this->show('Filter'); ?></button>
        </div>
        <?php endif; ?>

        <?php if ($filter->isApplied()): ?>
        <div class="btn-group mr-2">
            <a href="<?php echo $this->url('Shop:Admin:Browser@indexAction'); ?>" class="btn btn-primary"><i class="glyphicon glyphicon-trash"></i> <?php $this->show('Reset filter'); ?></a>
        </div>
        <?php endif; ?>
    </div>

    <div class="card">
        <?php $this->loadPartial('items-per-page', array('caption' => 'Products')); ?>

        <?php if (isset($categoryId)): ?>
        <?php echo Element::hidden($filter->getElementName('category_id'), $categoryId); ?>
        <?php endif; ?>

        <div class="table-responsive">
            <?= $this->widget(new GridViewWidget($products, [
                'batch' => true,
                'pk' => 'id',
                'tableClass' => 'table table-hover table-bordered',
                'columns' => [
                    [
                        'column' => 'id',
                        'label' => '#'
                    ],

                    [
                        'column' => 'image',
                        'label' => 'Cover',
                        'value' => function($product){
                            $image = Element::image($product->getImageBag()->getUrl('200x200'), array('class' => 'img-fluid'));
                            return Element::link($image, $product->getImageBag()->getUrl('original'), array(
                                'data-toggle' => 'tooltip',
                                'data-placement' => 'top',
                                'data-original-title' => $this->translate('Click to zoom this image'),
                                'data-lightbox' => sprintf('image-%s', $product->getId())
                            ));
                        }
                    ],

                    [
                        'column' => 'name',
                        'filter' => true
                    ],

                    [
                        'column' => 'date',
                        'filter' => true
                    ],

                    [
                        'column' => 'regular_price',
                        'label' => 'Price',
                        'filter' => true,
                        'value' => function($product){
                            return Element::number(sprintf('regular_price[%s]', $product->getId()), $product->getPrice(), array('class' => 'form-control center-block', 'min' => '0'));
                        }
                    ],

                    [
                        'column' => 'published',
                        'type' => 'select',
                        'filter' => 'boolean',
                        'value' => function($product){
                            return Element::checkbox(sprintf('published[%s]', $product->getId()), $product->getPublished());
                        }
                    ],

                    [
                        'column' => 'seo',
                        'label' => 'SEO',
                        'type' => 'select',
                        'filter' => 'boolean',
                        'value' => function($product){
                            return Element::checkbox(sprintf('seo[%s]', $product->getId()), $product->getSeo());
                        }
                    ]
                ],

                'actions' => [
                    'view' => function($product){
                        return Icon::view($product->getUrl(), $this->translate('View this product on site'));
                    },

                    'edit' => function($product){
                        return Icon::edit(
                            $this->url('Shop:Admin:Product@editAction', $product->getId()),
                            $this->translate('Edit this product')
                        );
                    },

                    'remove' => function($product){
                        return Icon::remove(
                            $this->url('Shop:Admin:Product@deleteAction', $product->getId()),
                            $this->translate('Remove this product')
                        );
                    }
                ]
            ])); ?>

            <?php if (empty($products)): ?>
            <div class="center-block">
                <h2 class="text-center text-muted"><i class="glyphicon glyphicon-remove"></i> <?php $this->show('No products'); ?></h2>
            </div>
            <?php endif; ?>
        </div>

        <?php $this->loadPartial('paginator'); ?>
    </div>

</form>

<div class="card">
    <h4><i class="glyphicon glyphicon-th-list"></i> <?php $this->show('Categories'); ?> (<?php echo count($categories); ?>)</h4>

    <?= $this->widget(new GridViewWidget($categories, [
        'tableClass' => 'table table-hover table-bordered table-striped',
        'rowAttributes' => array(
            'class' => function($category) use ($categoryId){
                return $categoryId == $category['id'] ? 'table-info' : null;
            }
        ),

        'columns' => [
            [
                'column' => 'id',
                'label' => '#'
            ],

            [
                'column' => 'name',
                'value' => function($category){
                    return Element::link($category['name'], $this->url('Shop:Admin:Browser@categoryAction', $category['id']));
                }
            ],

            [
                'column' => 'product_count',
                'label' => 'Amount of products'
            ]
        ],

        'actions' => [
            'view' => function($category){
                return Icon::view($category['url'], $this->translate('View this category'));
            },

            'edit' => function($row){
                return Icon::edit(
                    $this->url('Shop:Admin:Category@editAction', $row['id']),
                    $this->translate('Edit this category')
                );
            },

            'remove' => function($row){
                return Icon::remove(
                    $this->url('Shop:Admin:Category@deleteAction', $row['id']),
                    $this->translate('Remove this advice')
                );
            }
        ]
    ])); ?>

    <?php if (empty($categories)): ?>
    <div class="center-block">
        <h2 class="text-center text-muted"><i class="glyphicon glyphicon-remove"></i> <?php $this->show('No categories'); ?></h2>
    </div>
    <?php endif; ?>
</div>

<div class="modal fade" id="statistic-modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
 <div class="modal-dialog">
  <div class="modal-content">
    <div class="modal-header">
      <h4 class="modal-title"><i class="glyphicon glyphicon-calendar"></i> <?php $this->show('Statistic'); ?></h4>
      <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
    </div>
    <div class="modal-body" id="statistic-body"></div>
    <div class="modal-footer">
        <button type="button" class="btn btn-primary" data-dismiss="modal"><i class="glyphicon glyphicon-ok"></i> OK</button>
    </div>
 </div>
 </div>
</div>
