<?php

use Krystal\Form\Element;
use Cms\Service\LanguageManager;

defined('KRYSTAL') or die;

?>

<form class="card" data-group="category" autocomplete="off">
    <ul class="nav nav-tabs" role="tablist">
        <li class="nav-item">
            <a class="nav-link active" href="#page" role="tab" data-toggle="tab">
                <i class="bi bi-file-earmark"></i> <?= $this->translate('Category'); ?>
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="#configuration" role="tab" data-toggle="tab">
                <i class="bi bi-card-list"></i> <?= $this->translate('Configuration'); ?>
            </a>
        </li>
    </ul>

    <div class="card-body tab-content">
        <div class="tab-pane fade show active" id="page" role="tabpanel">
            <?php $this->loadPartial('language-tabs'); ?>

            <div class="tab-content mt-3">
                <?php foreach ($languages as $index => $language): ?>
                <div class="tab-pane fade <?= $index == 0 ? 'active show' : null; ?>" id="<?php printf('language-%s', $language->getId()); ?>" role="tabpanel">

                    <?php $entity = LanguageManager::findByLangId($language->getId(), $category); ?>

                    <?= Element::hidden(sprintf('translation[%s][id]', $language->getId()), $entity->getId()); ?>
                    <?= Element::hidden(sprintf('translation[%s][lang_id]', $language->getId()), $language->getId()); ?>
                    <?= Element::hidden(sprintf('translation[%s][web_page_id]', $language->getId()), $entity->getWebPageId()); ?>

                    <?php $this->loadPartial('language-name', ['language' => $language]); ?>

                    <div class="form-group row">
                        <label class="col-lg-2 col-form-label"><?= $this->translate('Name'); ?></label>
                        <div class="col-lg-10">
                            <div class="input-group">
                                <?= Element::text(sprintf('translation[%s][name]', $language->getId()), $entity->getName(), ['class' => 'form-control', 'placeholder' => $this->translate('Category name')]); ?>
                                <div class="input-group-append">
                                    <span class="input-group-text"><i class="bi bi-pencil"></i></span>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="form-group row">
                        <label class="col-lg-2 col-form-label"><?= $this->translate('Description'); ?></label>
                        <div class="col-lg-10">
                            <?= Element::textarea(sprintf('translation[%s][description]', $language->getId()), $entity->getDescription(), ['data-wysiwyg' => 'true']); ?>
                        </div>
                    </div>

                    <div class="options mt-4">
                        <div class="form-group row">
                            <label class="col-lg-2 col-form-label"><?= $this->translate('Slug'); ?></label>
                            <div class="col-lg-10">
                                <div class="input-group">
                                    <?= Element::text(sprintf('translation[%s][slug]', $language->getId()), $entity->getSlug(), ['class' => 'form-control', 'placeholder' => $this->translate('URL slug for this category. By default its taken from the name')]); ?>

                                    <div class="input-group-append">
                                        <span class="input-group-text">
                                            <a href="#" data-slug-selector="<?= LanguageManager::generateSelector($language->getId()); ?>"><i class="bi bi-arrow-repeat" data-toggle="tooltip" title="<?= $this->translate('Refresh the slug'); ?>"></i></a>
                                        </span>
                                    </div>
                                </div>
                            </div>
                        </div>

                        <div class="form-group row">
                            <label class="col-lg-2 col-form-label"><?= $this->translate('Change frequency'); ?></label>
                            <div class="col-lg-10">
                                <?= Element::select(sprintf('translation[%s][changefreq]', $language->getId()), $this->translateArray($changeFreqs), $entity->getChangeFreq(), ['class' => 'form-control']); ?>
                            </div>
                        </div>

                        <div class="form-group row">
                            <label class="col-lg-2 col-form-label"><?= $this->translate('Priority'); ?></label>
                            <div class="col-lg-10">
                                <?= Element::select(sprintf('translation[%s][priority]', $language->getId()), $priorities, $entity->getPriority(), ['class' => 'form-control']); ?>
                            </div>
                        </div>

                        <div class="form-group row">
                            <label class="col-lg-2 col-form-label"><?= $this->translate('Title'); ?></label>
                            <div class="col-lg-10">
                                <div class="input-group">
                                    <?= Element::text(sprintf('translation[%s][title]', $language->getId()), $entity->getTitle(), ['class' => 'form-control', 'data-input' => 'title', 'placeholder' => $this->translate('Category title')]); ?>
                                    <div class="input-group-append">
                                        <span class="input-group-text"><i class="bi bi-pencil"></i></span>
                                    </div>
                                </div>
                            </div>
                        </div>

                        <div class="form-group row">
                            <label class="col-lg-2 col-form-label"><?= $this->translate('Keywords'); ?></label>
                            <div class="col-lg-10">
                                <?= Element::textarea(sprintf('translation[%s][keywords]', $language->getId()), $entity->getKeywords(), ['class' => 'form-control', 'placeholder' => $this->translate('Keywords used for search engines')]); ?>
                            </div>
                        </div>
                        
                        <div class="form-group row">
                            <label class="col-lg-2 col-form-label"><?= $this->translate('Description'); ?></label>
                            <div class="col-lg-10">
                                <?= Element::textarea(sprintf('translation[%s][meta_description]', $language->getId()), $entity->getMetaDescription(), ['class' => 'form-control', 'placeholder' => $this->translate('Meta description for search engines')]); ?>
                            </div>
                        </div>
                    </div>
                </div>
                <?php endforeach; ?>
            </div>

            <?php $this->loadPartial('actions', [
                'new' => !$entity->getId(),
                'add' => 'Shop:Admin:Category@addAction',
                'edit' => 'Shop:Admin:Category@editAction',
                'save' => 'Shop:Admin:Category@saveAction',
                'cancel' => 'Shop:Admin:Browser@indexAction',
                'options' => true
            ]); ?>

        </div>
        
        <div role="tabpanel" class="tab-pane fade" id="configuration">
            <?= Element::hidden('category[id]', $entity->getId()); ?>
            <?= Element::hidden('category[cover]', $entity->getCover()); ?>

            <div class="form-group row">
                <label class="col-lg-2 col-form-label"><?= $this->translate('Enable SEO'); ?></label>
                <div class="col-lg-10">
                    <div class="form-check pt-2">
                        <?= Element::checkbox('category[seo]', $entity->getSeo(), ['class' => 'form-check-input', 'id' => 'category_seo']); ?>
                        <label class="form-check-label" for="category_seo"><?= $this->translate('Enable'); ?></label>
                    </div>
                </div>
            </div>

            <div class="form-group row">
                <label class="col-lg-2 col-form-label"><?= $this->translate('Order'); ?></label>
                <div class="col-lg-10">
                    <div class="input-group">
                        <?= Element::text('category[order]', $entity->getOrder(), ['class' => 'form-control', 'placeholder' => $this->translate('Category order')]); ?>
                        <div class="input-group-append">
                            <span class="input-group-text"><i class="bi bi-pencil"></i></span>
                        </div>
                    </div>
                </div>
            </div>

            <div class="form-group row">
                <label class="col-lg-2 col-form-label"><?= $this->translate('Parent category'); ?></label>
                <div class="col-lg-10">
                    <?= Element::select('category[parent_id]', $categories, $entity->getParentId(), ['class' => 'form-control']); ?>
                </div>
            </div>

            <div class="form-group row">
                <label class="col-lg-2 col-form-label"><?= $this->translate('Сover'); ?></label>
                <div class="col-lg-10">
                    <?php if ($entity->hasCover()): ?>
                    <div class="mb-3">
                        <img class="img-thumbnail" src="<?= $entity->getImageBag()->getUrl('200x200'); ?>" />
                    </div>
                    <div class="form-check mb-3">
                        <input class="form-check-input" type="checkbox" id="removeCover" name="category[remove_cover]" data-toggle="tooltip" title="<?= $this->translate('Check it if you want to remove this cover'); ?>" />
                        <label class="form-check-label" for="removeCover"><?= $this->translate('Remove this cover'); ?></label>
                    </div>
                    <?php else: ?>
                    <div class="mb-3">
                        <img class="img-thumbnail" data-image="preview" />
                    </div>
                    <?php endif; ?>

                    <a class="btn btn-primary" data-button="upload" data-target="[name='file']" href="#">
                        <i class="bi bi-image"></i> <?= $this->translate('Upload a file'); ?>
                    </a>
                    <?= Element::file('file', 'image/x-png, image/gif, image/jpeg', ['class' => 'd-none']); ?>
                </div>
            </div>
        </div>
    </div>
</form>