<?php

use Krystal\Form\Widget\DropdownWidget;
use Krystal\Form\HtmlHelper;
use Krystal\Form\Element;

?>

<form>
	<ul class="nav nav-tabs" role="tablist">
		<li role="presentation" class="active"><a href="#page" role="tab" data-toggle="tab"><i class="glyphicon glyphicon-file"></i> <?php $this->show('Category'); ?></a></li>
		<li role="presentation"><a href="#menu" role="tab" data-toggle="tab"><i class="glyphicon glyphicon-list"></i> <?php $this->show('Item in menu'); ?></a></li>
	</ul>
	
	<div class="tab-content">
		<div class="tab-pane fade in active" id="page" role="tabpanel">
			<div class="well clearfix">
				
				<!--Special hidden value for menu widget. That's a workaround-->
                <?php echo Element::hidden('web_page_id', $category->getWebPageId()); ?>
                <?php echo Element::hidden('category[id]', $category->getId()); ?>
                <?php echo Element::hidden('category[web_page_id]', $category->getWebPageId()); ?>
                <?php echo Element::hidden('category[cover]', $category->getCover()); ?>
				
				<div class="form-group clearfix">
					<label class="col-lg-2 control-label"><?php $this->show('Title'); ?></label>
					<div class="col-lg-10">
						<div class="input-group">
                            <?php echo Element::text('category[title]', $category->getTitle(), array('class' => 'form-control', 'data-input' => 'title', 'placeholder' => $this->translate('Category title'))); ?>
							<span class="input-group-addon"><i class="glyphicon glyphicon-pencil"></i></span>
						</div>
					</div>
				</div>
				
				<div class="form-group clearfix">
					<label class="col-lg-2 control-label"><?php $this->show('Parent category'); ?></label>
					<div class="col-lg-10">
                        <?php echo DropdownWidget::render(array('name' => 'category[parent_id]', 'class' => 'form-control'), $categories, $category->getParentId(), '— '.$this->translate('None').' —'); ?>
					</div>
				</div>
				
				<div class="form-group clearfix">
					<label class="col-lg-2 control-label"><?php $this->show('Description'); ?></label>
					<div class="col-lg-10">
                        <?php echo Element::textarea('category[description]', $category->getDescription()); ?>
					</div>
				</div>
				
				<div class="options">
					<div class="form-group clearfix">
						<label class="col-lg-2 control-label"><?php $this->show('Enable SEO'); ?></label>
						<div class="col-lg-10">
                            <?php echo Element::checkbox('category[seo]', $category->getSeo(), array('class' => 'form-control')); ?>
						</div>
					</div>
					
					<div class="form-group clearfix">
						<label class="col-lg-2 control-label"><?php $this->show('Order'); ?></label>
						<div class="col-lg-10">
							<div class="input-group">
                                <?php echo Element::text('category[order]', $category->getOrder(), array('class' => 'form-control', 'placeholder' => $this->translate('Category order'))); ?>
								<span class="input-group-addon"><i class="glyphicon glyphicon-pencil"></i></span>
							</div>
						</div>
					</div>
					
					<div class="form-group clearfix">
						<label class="col-lg-2 control-label"><?php $this->show('Slug'); ?></label>
						<div class="col-lg-10">
							<div class="input-group">
                                <?php echo Element::text('category[slug]', $category->getSlug(), array('class' => 'form-control', 'data-input' => 'slug', 'placeholder' => $this->translate('URL slug for this category. By default is taken from a title'))); ?>
								<span class="input-group-addon">
									<a href="#" data-button="slug"><i class="glyphicon glyphicon-refresh" data-toggle="tooltip" title="<?php $this->show('Refresh the slug'); ?>"></i></a>
								</span>
							</div>
						</div>
					</div>
					
					<div class="form-group clearfix">
						<label class="col-lg-2 control-label"><?php $this->show('Keywords'); ?></label>
						<div class="col-lg-10">
							<div class="input-group">
								<?php echo Element::text('category[keywords]', $category->getKeywords(), array('class' => 'form-control', 'placeholder' => $this->translate('Keywords used for search engines'))); ?>
								<span class="input-group-addon"><i class="glyphicon glyphicon-tags"></i></span>
							</div>
						</div>
					</div>
					
					<div class="form-group clearfix">
						<label class="col-lg-2 control-label"><?php $this->show('Description'); ?></label>
						<div class="col-lg-10">
                            <?php echo Element::textarea('category[meta_description]', $category->getMetaDescription(), array('class' => 'form-control', 'placeholder' => $this->translate('Meta description for search engines'))); ?>
						</div>
					</div>
					
					<div class="form-group clearfix">
						<label class="col-lg-2 control-label"><?php $this->show('Сover'); ?></label>
						<div class="col-lg-10">

							<?php if ($category->hasCover()): ?>

							<img src="<?php echo $category->getImageBag()->getUrl('200x200'); ?>" />

							<br />
							<br />

							<div>
								<label for="removeCover"><?php $this->show('Remove this cover'); ?>&nbsp;</label>
								<input type="checkbox" id="removeCover" name="category[remove_cover]" data-toggle="tooltip" data-placement="left" title="<?php $this->show('Check it if you want to remove this cover'); ?>" />
							</div>
							
							<?php else: ?>
							
							<img data-image="preview" />
							
							<?php endif; ?>
							
							<br />
							<br />
							
                            <?php echo Element::file('file', 'image/x-png, image/gif, image/jpeg'); ?>
						</div>
					</div>
				</div>
			</div>
			
			<?php if ($category->getId()): ?>
            
			<button data-button="save" data-url="<?php echo $this->url('Shop:Admin:Category:Edit@updateAction'); ?>" class="btn btn-primary"><i class="glyphicon glyphicon-floppy-save"></i> <?php $this->show('Save'); ?></button>
			<button data-button="save-create" data-back-url="<?php echo $this->url('Shop:Admin:Category:Add@indexAction'); ?>" data-url="<?php echo $this->url('Shop:Admin:Category:Edit@updateAction'); ?>" class="btn btn-primary"><i class="glyphicon glyphicon-floppy-open"></i> <?php $this->show('Save & Create new'); ?></button>
			
			<?php else: ?>
			
            <button data-button="add" data-back-url="<?php echo $this->url('Shop:Admin:Category:Edit@indexAction', null); ?>" data-url="<?php echo $this->url('Shop:Admin:Category:Add@addAction'); ?>" class="btn btn-primary"><i class="glyphicon glyphicon-floppy-save"></i> <?php $this->show('Add'); ?></button>
			<button data-button="add-create" data-url="<?php echo $this->url('Shop:Admin:Category:Add@addAction'); ?>" class="btn btn-primary"><span class="glyphicon glyphicon-floppy-open"></span> <?php $this->show('Add & Create new'); ?></button>
			
			<?php endif; ?>
			
			<button data-button="options" class="btn btn-primary"><i class="glyphicon glyphicon-open"></i> <?php $this->show('More options'); ?></button>
			<button data-button="cancel" data-url="<?php echo $this->url('Shop:Admin:Browser@indexAction'); ?>" class="btn btn-default"><i class="glyphicon glyphicon-floppy-remove"></i> <?php $this->show('Cancel'); ?></button>
			
		</div>
		
		<div class="tab-pane fade" id="menu" role="tabpanel">
			<?php $this->loadBlock('menu-widget'); ?>
		</div>
	</div>
</form>
