<?php

use Krystal\Form\Element;
use Krystal\Widget\GridView\GridViewWidget;
use Cms\View\Icon;

defined('KRYSTAL') or die;

?>

<div class="row">
    <div class="col-lg-6 mb-4">
        <div class="card">
            <div class="card-header">
                <h3 class="card-title m-0">
                    <i class="bi bi-card-heading"></i> <?php $this->show('Available coupons'); ?> 
                    <small class="text-muted">(<?= count($coupons); ?>)</small>
                </h3>
            </div>

            <div class="card-body table-responsive">
                <?= $this->widget(new GridViewWidget($coupons, [
                    'tableClass' => 'table table-hover table-bordered table-striped',
                    'rowAttributes' => [
                        'class' => function($row) use ($coupon){
                            return $coupon->getId() == $row->getId() ? 'table-info' : null;
                        }
                    ],
                    'columns' => [
                        [
                            'column' => 'id',
                            'label' => '#'
                        ],
                        [
                            'column' => 'code'
                        ],
                        [
                            'column' => 'percentage',
                            'value' => function($coupon){
                                return $coupon->getPercentage() . ' % ';
                            }
                        ],
                    ],

                    'actions' => [
                        function($coupon){
                            return Icon::edit(
                                $this->url('Shop:Admin:Coupon@editAction', $coupon->getId()),
                                $this->translate('Edit this coupon')
                            );
                        },
                        function($coupon){
                            return Icon::remove(
                                $this->url('Shop:Admin:Coupon@deleteAction', $coupon->getId()),
                                $this->translate('Remove this coupon'),
                                null,
                                $this->url('Shop:Admin:Coupon@indexAction')
                            );
                        }
                    ]
                ])); ?>
            </div>
        </div>
    </div>

    <div class="col-lg-6">
        <div class="card">
            <div class="card-header">
                <h3 class="card-title m-0">
                    <i class="bi bi-pencil"></i> <?php $this->show($coupon->getId() ? 'Update coupon' : 'Add new coupon'); ?>
                </h3>
            </div>

            <div class="card-body">
                <form data-group="coupon" autocomplete="off">
                    <input type="hidden" name="coupon[id]" value="<?= $coupon->getId(); ?>" />

                    <div class="form-group mb-3">
                        <label class="form-label"><?php $this->show('Code'); ?></label>
                        <div class="input-group">
                            <?= Element::text('coupon[code]', $coupon->getCode(), ['class' => 'form-control', 'placeholder' => $this->translate('Unique coupon code')]); ?>
                            <div class="input-group-append">
                                <span class="input-group-text"><i class="bi bi-pencil"></i></span>
                            </div>
                        </div>
                    </div>

                    <div class="form-group mb-3">
                        <label class="form-label"><?php $this->show('Percentage'); ?></label>
                        <div class="input-group">
                            <?= Element::number('coupon[percentage]', $coupon->getPercentage(), ['min' => 1, 'max' => 100, 'class' => 'form-control', 'placeholder' => $this->translate('Discount percentage')]); ?>
                            <div class="input-group-append">
                                <span class="input-group-text"><i class="bi bi-pencil"></i></span>
                            </div>
                        </div>
                    </div>

                    <?php $this->loadPartial('actions', [
                        'new' => !$coupon->getId(),
                        'add' => 'Shop:Admin:Coupon@indexAction',
                        'edit' => 'Shop:Admin:Coupon@editAction',
                        'save' => 'Shop:Admin:Coupon@saveAction',
                        'cancel' => 'Shop:Admin:Coupon@indexAction'
                    ]); ?>
                </form>
            </div>
        </div>
    </div>
</div>