<?php

use Krystal\Form\Element;
use Krystal\Grid\Grid;
use Cms\View\Icon;

defined('KRYSTAL') or die;

?>

<div class="row">
    <div class="col-lg-6">
        <h2 class="page-header"><i class="glyphicon glyphicon-list-alt"></i> <?php $this->show('Available coupons'); ?> <small>(<?php echo count($coupons); ?>)</small></h2>

        <div class="table-responsive">
            <?= Grid::render($coupons, array(
                'tableClass' => 'table table-hover table-bordered table-striped table-condensed',
                'rowAttributes' => array(
                    'class' => function($coupon) use ($entity){
                        return $entity->getId() == $coupon->getId() ? 'info' : null;
                    }
                ),
                'columns' => array(
                    array(
                        'column' => 'id',
                        'label' => '#'
                    ),

                    array(
                        'column' => 'code'
                    ),
                    
                    array(
                        'column' => 'percentage',
                        'value' => function($coupon){
                            return $coupon->getPercentage() . ' % ';
                        }
                    ),
                ),

                'actions' => array(
                    'edit' => function($coupon){
                        return Icon::edit(
                            $this->url('Shop:Admin:Coupon@editAction', $coupon->getId()),
                            $this->translate('Edit this coupon')
                        );
                    },

                    'remove' => function($coupon){
                        return Icon::remove(
                            $this->url('Shop:Admin:Coupon@deleteAction', $coupon->getId()),
                            $this->translate('Remove this coupon'),
                            null,
                            $this->url('Shop:Admin:Coupon@indexAction')
                        );
                    }
                )

            ), $this->translator); ?>
        </div>
    </div>

    <div class="col-lg-6">
        <h3 class="page-header"><i class="glyphicon glyphicon-pencil"></i> <?php $this->show($coupon->getId() ? 'Update coupon' : 'Add new coupon'); ?></h3>

        <form data-group="coupon">
            <div class="well">
                <input type="hidden" name="coupon[id]" value="<?php echo $coupon->getId(); ?>" />

                <div class="form-group">
                    <label class="col-lg-2 control-label"><?php $this->show('Code'); ?></label>
                    <div class="col-lg-10">
                        <div class="input-group">
                            <?php echo Element::text('coupon[code]', $coupon->getCode(), array('class' => 'form-control', 'placeholder' => $this->translate('Unique coupon code'))); ?>
                            <span class="input-group-addon"><i class="glyphicon glyphicon-pencil"></i></span>
                        </div>
                    </div>
                </div>

                <div class="form-group">
                    <label class="col-lg-2 control-label"><?php $this->show('Percentage'); ?></label>
                    <div class="col-lg-10">
                        <div class="input-group">
                            <?php echo Element::number('coupon[percentage]', $coupon->getPercentage(), array('min' => 1, 'max' => 100, 'class' => 'form-control', 'placeholder' => $this->translate('Discount percentage'))); ?>
                            <span class="input-group-addon"><i class="glyphicon glyphicon-pencil"></i></span>
                        </div>
                    </div>
                </div>
            </div>

            <?php if (!$coupon->getId()): ?>

            <button data-button="add" data-back-url="<?php echo $this->url('Shop:Admin:Coupon@editAction', null); ?>" data-url="<?php echo $this->url('Shop:Admin:Coupon@saveAction'); ?>" class="btn btn-primary"><i class="glyphicon glyphicon-floppy-save"></i> <?php $this->show('Add'); ?></button>
            <button data-button="add-create" data-url="<?php echo $this->url('Shop:Admin:Coupon@saveAction'); ?>" class="btn btn-primary"><i class="glyphicon glyphicon-floppy-save"></i> <?php $this->show('Add & Create new'); ?></button>

            <?php else: ?>

            <button data-button="save" data-url="<?php echo $this->url('Shop:Admin:Coupon@saveAction'); ?>" class="btn btn-primary"><i class="glyphicon glyphicon-floppy-save"></i> <?php $this->show('Save'); ?></button>
            <button data-button="save-create" data-back-url="<?php echo $this->url('Shop:Admin:Coupon@indexAction'); ?>" data-url="<?php echo $this->url('Shop:Admin:Coupon@saveAction'); ?>" class="btn btn-primary"><i class="glyphicon glyphicon-floppy-save"></i> <?php $this->show('Save & Create new'); ?></button>
            <button data-button="cancel" data-url="<?php echo $this->url('Shop:Admin:Coupon@indexAction'); ?>" class="btn btn-default"><i class="glyphicon glyphicon-floppy-remove"></i> <?php $this->show('Cancel'); ?></button>

            <?php endif; ?>
        </form>
    </div>
</div>
