<?php

use Krystal\Form\Element;
use Krystal\Widget\GridView\GridViewWidget;
use Cms\View\Icon;

?>

<div class="row">
    <div class="col-lg-6 mb-4">
        <div class="card">
            <div class="card-header">
                <h3 class="card-title m-0">
                    <i class="bi bi-cash-stack"></i> <?= $this->translate('Available currencies'); ?>
                    <small class="text-muted">(<?= count($currencies); ?>)</small>
                </h3>
            </div>

            <div class="card-body table-responsive">
                <?= $this->widget(new GridViewWidget($currencies, [
                    'tableClass' => 'table table-hover table-bordered table-striped',
                    'rowAttributes' => [
                        'class' => function($row) use ($currency){
                            return $row->getId() == $currency->getId() ? 'table-info' : null;
                        }
                    ],
                    'columns' => [
                        ['column' => 'id', 'label' => '#'],
                        ['column' => 'value'],
                        ['column' => 'code', 'label' => 'Currency code']
                    ],
                    'actions' => [
                        function($currency){
                            return Icon::edit(
                                $this->url('Shop:Admin:Currency@editAction', $currency->getId()),
                                $this->translate('Edit this currency')
                            );
                        },
                        function($currency){
                            return Icon::remove(
                                $this->url('Shop:Admin:Currency@deleteAction', $currency->getId()),
                                $this->translate('Remove this currency'),
                                null,
                                $this->url('Shop:Admin:Currency@indexAction')
                            );
                        }
                    ]
                ])); ?>
            </div>
        </div>
    </div>

    <div class="col-lg-6">
        <div class="card">
            <div class="card-header">
                <h3 class="card-title m-0">
                    <i class="bi bi-pencil"></i> <?= $this->translate($currency->getId() ? 'Update currency' : 'Add new currency'); ?>
                </h3>
            </div>

            <div class="card-body">
                <form autocomplete="off">
                    <?= Element::hidden('currency[id]', $currency->getId()); ?>

                    <div class="mb-3">
                        <label class="form-label"><?= $this->translate('Code'); ?></label>
                        <div class="input-group">
                            <?= Element::text('currency[code]', $currency->getCode(), ['class' => 'form-control', 'placeholder' => $this->translate('Unique currency code')]); ?>
                            <span class="input-group-text"><i class="bi bi-pencil"></i></span>
                        </div>
                    </div>

                    <div class="mb-3">
                        <label class="form-label"><?= $this->translate('Value'); ?></label>
                        <div class="input-group">
                            <?= Element::text('currency[value]', $currency->getValue(), ['class' => 'form-control', 'placeholder' => $this->translate('Currency value')]); ?>
                            <span class="input-group-text"><i class="bi bi-pencil"></i></span>
                        </div>
                    </div>

                    <?php $this->loadPartial('actions', [
                        'new' => !$currency->getId(),
                        'add' => 'Shop:Admin:Currency@indexAction',
                        'edit' => 'Shop:Admin:Currency@editAction',
                        'save' => 'Shop:Admin:Currency@saveAction',
                        'cancel' => 'Shop:Admin:Currency@indexAction'
                    ]); ?>
                </form>
            </div>
        </div>
    </div>
</div>