<?php

use Krystal\Form\Element;
use Krystal\Grid\Grid;
use Cms\View\Icon;

defined('KRYSTAL') or die;

?>

<div class="row">
    <div class="col-lg-6">
        <h2 class="page-header"><i class="glyphicon glyphicon-list-alt"></i> <?php $this->show('Available currencies'); ?> <small>(<?php echo count($currencies); ?>)</small></h2>

        <div class="table-responsive">
            <?= Grid::render($currencies, array(
                'tableClass' => 'table table-hover table-bordered table-striped table-condensed',
                'rowAttributes' => array(
                    'class' => function($row) use ($currency){
                        return $row->getId() == $currency->getId() ? 'info' : null;
                    }
                ),

                'columns' => array(
                    array(
                        'column' => 'id',
                        'label' => '#'
                    ),

                    array(
                        'column' => 'value'
                    ),

                    array(
                        'column' => 'code',
                        'label' => 'Currency code'
                    )
                ),

                'actions' => array(
                    'edit' => function($currency){
                        return Icon::edit(
                            $this->url('Shop:Admin:Currency@editAction', $currency->getId()),
                            $this->translate('Edit this currency')
                        );
                    },

                    'remove' => function($currency){
                        return Icon::remove(
                            $this->url('Shop:Admin:Currency@deleteAction', $currency->getId()),
                            $this->translate('Remove this currency'),
                            null,
                            $this->url('Shop:Admin:Currency@indexAction')
                        );
                    }
                )

            ), $this->translator); ?>            
        </div>
    </div>

    <div class="col-lg-6">
        <h3 class="page-header"><i class="glyphicon glyphicon-pencil"></i> <?php $this->show($currency->getId() ? 'Update currency' : 'Add new currency'); ?></h3>

        <form data-group="currency">
            <div class="well">
                <input type="hidden" name="currency[id]" value="<?php echo $currency->getId(); ?>" />

                <div class="form-group">
                    <label class="col-lg-2 control-label"><?php $this->show('Code'); ?></label>
                    <div class="col-lg-10">
                        <div class="input-group">
                            <?php echo Element::text('currency[code]', $currency->getCode(), array('class' => 'form-control', 'placeholder' => $this->translate('Unique currency code'))); ?>
                            <span class="input-group-addon"><i class="glyphicon glyphicon-pencil"></i></span>
                        </div>
                    </div>
                </div>

                <div class="form-group">
                    <label class="col-lg-2 control-label"><?php $this->show('Value'); ?></label>
                    <div class="col-lg-10">
                        <div class="input-group">
                            <?php echo Element::text('currency[value]', $currency->getValue(), array('class' => 'form-control', 'placeholder' => $this->translate('Currency value'))); ?>
                            <span class="input-group-addon"><i class="glyphicon glyphicon-pencil"></i></span>
                        </div>
                    </div>
                </div>
            </div>

            <?php if (!$currency->getId()): ?>

            <button data-button="add" data-back-url="<?php echo $this->url('Shop:Admin:Currency@editAction', null); ?>" data-url="<?php echo $this->url('Shop:Admin:Currency@saveAction'); ?>" class="btn btn-primary"><i class="glyphicon glyphicon-floppy-save"></i> <?php $this->show('Add'); ?></button>
            <button data-button="add-create" data-url="<?php echo $this->url('Shop:Admin:Currency@saveAction'); ?>" class="btn btn-primary"><i class="glyphicon glyphicon-floppy-save"></i> <?php $this->show('Add & Create new'); ?></button>

            <?php else: ?>

            <button data-button="save" data-url="<?php echo $this->url('Shop:Admin:Currency@saveAction'); ?>" class="btn btn-primary"><i class="glyphicon glyphicon-floppy-save"></i> <?php $this->show('Save'); ?></button>
            <button data-button="save-create" data-back-url="<?php echo $this->url('Shop:Admin:Currency@indexAction'); ?>" data-url="<?php echo $this->url('Shop:Admin:Currency@saveAction'); ?>" class="btn btn-primary"><i class="glyphicon glyphicon-floppy-save"></i> <?php $this->show('Save & Create new'); ?></button>
            <button data-button="cancel" data-url="<?php echo $this->url('Shop:Admin:Currency@indexAction'); ?>" class="btn btn-default"><i class="glyphicon glyphicon-floppy-remove"></i> <?php $this->show('Cancel'); ?></button>

            <?php endif; ?>
        </form>
    </div>
</div>
