<?php

use Krystal\Form\Element;
defined('KRYSTAL') or die;

?>

<div class="row">
    <div class="col-lg-6">
        <h2 class="page-header"><i class="glyphicon glyphicon-list-alt"></i> <?php $this->show('Available delivery types'); ?></h2>

        <div class="table-responsive">
            <table class="table table-stripped table-bordered table-hover">
                <thead>
                    <tr>
                        <td class="text-center text-muted">#</td>
                        <td class="text-center"><?php $this->show('Name'); ?></td>
                        <td class="text-center"><?php $this->show('Price'); ?></td>
                        <td class="text-center"><?php $this->show('Actions'); ?></td>
                    </tr>
                </thead>

                <tbody>
                    <?php foreach ($deliveryTypes as $entity): ?>
                    <tr class="<?php echo $entity->getId() == $deliveryType->getId() ? 'info' : null; ?>">
                        <td class="text-center text-muted"><?php echo $entity->getId(); ?></td>
                        <td class="text-center"><?php echo $entity->getName(); ?></td>
                        <td class="text-center"><?php echo $entity->getPrice(); ?></td>
                        <td class="text-center">
                            <a data-button="edit" data-toggle="tooltip" data-placement="left" data-original-title="<?php $this->show('Edit this delivery method'); ?>" href="<?php echo $this->url('Shop:Admin:DeliveryType@editAction', $entity->getId()); ?>"><i class="glyphicon glyphicon-pencil"></i></a>
                            <a data-button="delete" data-url="<?php echo $this->url('Shop:Admin:DeliveryType@deleteAction', $entity->getId()); ?>" data-toggle="tooltip" data-placement="left" data-original-title="<?php $this->show('Remove this delivery type'); ?>" href="#"><i class="glyphicon glyphicon-remove"></i></a>
                        </td>
                    </tr>
                    <?php endforeach; ?>
                </tbody>
            </table>
        </div>
    </div>

    <div class="col-lg-6">
        <h3 class="page-header"><i class="glyphicon glyphicon-pencil"></i> <?php $this->show($deliveryType->getId() ? 'Update delivery type' : 'Add new delivery type'); ?></h3>

        <form data-group="deliveryType">
            <div class="well">
                <input type="hidden" name="deliveryType[id]" value="<?php echo $deliveryType->getId(); ?>" />

                <div class="form-group">
                    <label class="col-lg-2 control-label"><?php $this->show('Name'); ?></label>
                    <div class="col-lg-10">
                        <div class="input-group">
                            <?php echo Element::text('deliveryType[name]', $deliveryType->getName(), array('class' => 'form-control', 'placeholder' => $this->translate('Name'))); ?>
                            <span class="input-group-addon"><i class="glyphicon glyphicon-pencil"></i></span>
                        </div>
                    </div>
                </div>

                <div class="form-group">
                    <label class="col-lg-2 control-label"><?php $this->show('Price'); ?></label>
                    <div class="col-lg-10">
                        <div class="input-group">
                            <?php echo Element::text('deliveryType[price]', $deliveryType->getPrice(), array('class' => 'form-control', 'placeholder' => $this->translate('Price'))); ?>
                            <span class="input-group-addon"><i class="glyphicon glyphicon-pencil"></i></span>
                        </div>
                    </div>
                </div>
            </div>

            <?php if (!$deliveryType->getId()): ?>

            <button data-button="add" data-back-url="<?php echo $this->url('Shop:Admin:DeliveryType@editAction', null); ?>" data-url="<?php echo $this->url('Shop:Admin:DeliveryType@saveAction'); ?>" class="btn btn-primary"><i class="glyphicon glyphicon-floppy-save"></i> <?php $this->show('Add'); ?></button>
            <button data-button="add-create" data-url="<?php echo $this->url('Shop:Admin:DeliveryType@saveAction'); ?>" class="btn btn-primary"><i class="glyphicon glyphicon-floppy-save"></i> <?php $this->show('Add & Create new'); ?></button>

            <?php else: ?>

            <button data-button="save" data-url="<?php echo $this->url('Shop:Admin:DeliveryType@saveAction'); ?>" class="btn btn-primary"><i class="glyphicon glyphicon-floppy-save"></i> <?php $this->show('Save'); ?></button>
            <button data-button="save-create" data-back-url="<?php echo $this->url('Shop:Admin:DeliveryType@indexAction'); ?>" data-url="<?php echo $this->url('Shop:Admin:DeliveryType@saveAction'); ?>" class="btn btn-primary"><i class="glyphicon glyphicon-floppy-save"></i> <?php $this->show('Save & Create new'); ?></button>
            <button data-button="cancel" data-url="<?php echo $this->url('Shop:Admin:DeliveryType@indexAction'); ?>" class="btn btn-default"><i class="glyphicon glyphicon-floppy-remove"></i> <?php $this->show('Cancel'); ?></button>

            <?php endif; ?>
        </form>
    </div>
</div>
