<style>
    .table-wrapper {
        overflow-y: scroll;
        max-height: 174px;
    }
</style>

<h4 class="mb-3">
    <i class="bi bi-cart"></i> <?= $this->translate('Order details'); ?>
    <small class="text-muted"># <?= $id; ?></small>
</h4>

<div class="table-wrapper mb-4">
    <table class="table table-hover table-bordered table-striped">
        <thead>
            <tr>
                <th class="text-center text-muted"><?= $this->translate('#'); ?></th>
                <th class="text-center"><?= $this->translate('Product'); ?></th>
                <th class="text-center"><?= $this->translate('SKU'); ?></th>
                <th class="text-center"><?= $this->translate('Price'); ?></th>
                <th class="text-center"><?= $this->translate('Sub total price'); ?></th>
                <th class="text-center"><?= $this->translate('Quantity'); ?></th>
                <th class="text-center"><?= $this->translate('Attributes'); ?></th>
            </tr>
        </thead>

        <?php if (!empty($details)): ?>
        <tbody>
            <?php foreach ($details as $detail): ?>
            <tr class="<?= !$detail['exists'] ? 'table-danger' : ''; ?>" title="<?= !$detail['exists'] ? $this->translate('This product is no longer available') : ''; ?>">
                <td class="text-center text-muted"><?= $detail['product_id']; ?></td>
                <td>
                    <?php if ($detail['exists']): ?>
                    <a target="_blank" href="<?= $detail['url']; ?>"><?= $detail['name']; ?></a>
                    <?php else: ?>
                    <?= $detail['name']; ?>
                    <?php endif; ?>
                </td>
                <td class="text-center"><?= $detail['sku']; ?></td>
                <td class="text-center"><?= number_format($detail['price']); ?> <?= $currency; ?></td>
                <td class="text-center"><?= number_format($detail['sub_total_price']); ?> <?= $currency; ?></td>
                <td class="text-center"><?= $detail['qty']; ?></td>
                <td class="text-center">
                    <?php foreach ($detail['attributes'] as $name => $value): ?>
                    <p class="m-0 small"><strong><?= $name; ?></strong>: <?= $value; ?></p>
                    <?php endforeach; ?>
                </td>
            </tr>
            <?php endforeach; ?>
        </tbody>
        <?php endif; ?>
    </table>
</div>

<h4 class="mb-3"><i class="bi bi-person"></i> <?= $this->translate('Customer details'); ?></h4>

<div class="table-wrapper">
    <table class="table table-bordered table-hover">
        <tbody>
            <tr>
                <td><strong><?= $this->translate('Order ID'); ?></strong></td>
                <td><?= $id; ?></td>
            </tr>
            <tr>
                <td><strong><?= $this->translate('Customer'); ?></strong></td>
                <td><?= $order->getName(); ?></td>
            </tr>
            <tr>
                <td><strong><?= $this->translate('Customer email'); ?></strong></td>
                <td><?= $order->getEmail(); ?></td>
            </tr>
            <tr>
                <td><strong><?= $this->translate('Customer address'); ?></strong></td>
                <td><?= $order->getAddress(); ?></td>
            </tr>
            <tr>
                <td><strong><?= $this->translate('Customer phone'); ?></strong></td>
                <td><?= $order->getPhone(); ?></td>
            </tr>
            <tr>
                <td><strong><?= $this->translate('Order date'); ?></strong></td>
                <td><?= $order->getDatetime(); ?></td>
            </tr>
            <tr>
                <td><strong><?= $this->translate('Order comment'); ?></strong></td>
                <td><?= $order->getComment(); ?></td>
            </tr>
            <tr class="table-light">
                <td><strong><?= $this->translate('Total quantity'); ?></strong></td>
                <td><strong><?= $summary['totalQty']; ?></strong></td>
            </tr>
            <tr class="table-light">
                <td><strong><?= $this->translate('Total price'); ?></strong></td>
                <td><strong><?= number_format($summary['totalPrice']); ?> <?= $currency; ?></strong></td>
            </tr>
        </tbody>
    </table>
</div>