<?php defined('KRYSTAL') or die; ?>
<?php

use Krystal\Form\Widget\BooleanWidget;
use Krystal\Form\Element;
use Krystal\Form\HtmlHelper;

?>

<div class="btn-toolbar">
	<div class="btn-group">
	  <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
		<span class="glyphicon glyphicon-list"></span> <?php $this->show('Menu'); ?> <span class="caret"></span>
	  </button>
      
	  <ul class="dropdown-menu">
         <li><a href="<?php echo $this->url('Shop:Admin:OrderStatus@indexAction'); ?>"><i class="glyphicon glyphicon-header"></i> <?php $this->show('Order statuses'); ?></a></li>
		 <li class="divider"></li>
         <?php if (!empty($orders)): ?>
		 <li><a href="#" data-button="save-changes" data-url="<?php echo $this->url('Shop:Admin:Order@tweakAction'); ?>"><i class="glyphicon glyphicon-floppy-save"></i> <?php $this->show('Save changes'); ?></a></li>
		 <li><a href="#" data-button="remove-selected" data-url="<?php echo $this->url('Shop:Admin:Order@deleteAction', null); ?>"><i class="glyphicon glyphicon-remove"></i> <?php $this->show('Remove selected'); ?></a></li>
         
         <?php else: ?>
		 
         <li class="disabled"><a><i class="glyphicon glyphicon-floppy-save"></i> <?php $this->show('Save changes'); ?></a></li>
		 <li class="disabled"><a><i class="glyphicon glyphicon-remove"></i> <?php $this->show('Remove selected'); ?></a></li>
         <?php endif; ?>
	  </ul>
	</div>
</div>

<h2><i class="glyphicon glyphicon-user"></i> <?php $this->show('Orders'); ?> (<?php echo $paginator->getTotalAmount(); ?>)</h2>

<div class="table-responsive">
    <?php $this->loadPartial('items-per-page', array('caption' => 'Recent orders')); ?>
    
    <form action="<?php echo $this->url('Shop:Admin:Order@filterAction', null); ?>" novalidate>
        <table class="table table-hover table-bordered table-striped">
            <thead>
                <tr>
                    <th></th>
                    <th class="text-center">
                        <a <?php echo HtmlHelper::addClassOnDemand($filter->isSortedBy('id'), 'text-info'); ?> href="<?php echo $filter->getColumnSortingUrl('id'); ?>"><i class="<?php echo $filter->isSortedByDesc('id') ? 'glyphicon glyphicon-arrow-down': 'glyphicon glyphicon-arrow-up'; ?>"></i> #</a>
                    </th>
                    <th class="text-center">
                        <a <?php echo HtmlHelper::addClassOnDemand($filter->isSortedBy('order_status_id'), 'text-info'); ?> href="<?php echo $filter->getColumnSortingUrl('order_status_id'); ?>"><i class="<?php echo $filter->isSortedByDesc('order_status_id') ? 'glyphicon glyphicon-arrow-down': 'glyphicon glyphicon-arrow-up'; ?>"></i> <?php $this->show('Order status'); ?></a>
                    </th>
                    <th class="text-center">
                        <a <?php echo HtmlHelper::addClassOnDemand($filter->isSortedBy('date'), 'text-info'); ?> href="<?php echo $filter->getColumnSortingUrl('date'); ?>"><i class="<?php echo $filter->isSortedByDesc('date') ? 'glyphicon glyphicon-arrow-down': 'glyphicon glyphicon-arrow-up'; ?>"></i> <?php $this->show('Date'); ?></a>
                    </th>
                    <th class="text-center">
                        <a <?php echo HtmlHelper::addClassOnDemand($filter->isSortedBy('name'), 'text-info'); ?> href="<?php echo $filter->getColumnSortingUrl('name'); ?>"><i class="<?php echo $filter->isSortedByDesc('name') ? 'glyphicon glyphicon-arrow-down': 'glyphicon glyphicon-arrow-up'; ?>"></i> <?php $this->show('Customer'); ?></a>
                    </th>
                    <th class="text-center">
                        <a <?php echo HtmlHelper::addClassOnDemand($filter->isSortedBy('email'), 'text-info'); ?> href="<?php echo $filter->getColumnSortingUrl('email'); ?>"><i class="<?php echo $filter->isSortedByDesc('name') ? 'glyphicon glyphicon-arrow-down': 'glyphicon glyphicon-arrow-up'; ?>"></i> <?php $this->show('Email'); ?></a>
                    </th>
                    <th class="text-center">
                        <a <?php echo HtmlHelper::addClassOnDemand($filter->isSortedBy('phone'), 'text-info'); ?> href="<?php echo $filter->getColumnSortingUrl('phone'); ?>"><i class="<?php echo $filter->isSortedByDesc('name') ? 'glyphicon glyphicon-arrow-down': 'glyphicon glyphicon-arrow-up'; ?>"></i> <?php $this->show('Phone'); ?></a>
                    </th>
                    <th class="text-center">
                        <a <?php echo HtmlHelper::addClassOnDemand($filter->isSortedBy('address'), 'text-info'); ?> href="<?php echo $filter->getColumnSortingUrl('address'); ?>"><i class="<?php echo $filter->isSortedByDesc('address') ? 'glyphicon glyphicon-arrow-down': 'glyphicon glyphicon-arrow-up'; ?>"></i> <?php $this->show('Address'); ?></a>
                    </th>
                    <th class="text-center"><?php $this->show('Comment'); ?></th>
                    <th class="text-center"><?php $this->show('Delivery type'); ?></th>
                    <th class="text-center">
                        <a <?php echo HtmlHelper::addClassOnDemand($filter->isSortedBy('qty'), 'text-info'); ?> href="<?php echo $filter->getColumnSortingUrl('qty'); ?>"><i class="<?php echo $filter->isSortedByDesc('address') ? 'glyphicon glyphicon-arrow-down': 'glyphicon glyphicon-arrow-up'; ?>"></i> <?php $this->show('Qty'); ?></a>
                    </th>
                    <th class="text-center">
                        <a <?php echo HtmlHelper::addClassOnDemand($filter->isSortedBy('total_price'), 'text-info'); ?> href="<?php echo $filter->getColumnSortingUrl('total_price'); ?>"><i class="<?php echo $filter->isSortedByDesc('total_price') ? 'glyphicon glyphicon-arrow-down': 'glyphicon glyphicon-arrow-up'; ?>"></i> <?php $this->show('Total price'); ?></a>
                    </th>
                    <th class="text-center">
                        <a <?php echo HtmlHelper::addClassOnDemand($filter->isSortedBy('discount'), 'text-info'); ?> href="<?php echo $filter->getColumnSortingUrl('discount'); ?>"><i class="<?php echo $filter->isSortedByDesc('discount') ? 'glyphicon glyphicon-arrow-down': 'glyphicon glyphicon-arrow-up'; ?>"></i> <?php $this->show('Discount'); ?></a>
                    </th>
                    <th class="text-center">
                        <a <?php echo HtmlHelper::addClassOnDemand($filter->isSortedBy('approved'), 'text-info'); ?> href="<?php echo $filter->getColumnSortingUrl('approved'); ?>"><i class="<?php echo $filter->isSortedByDesc('approved') ? 'glyphicon glyphicon-arrow-down': 'glyphicon glyphicon-arrow-up'; ?>"></i> <?php $this->show('Approved'); ?></a>
                    </th>
                    <th class="text-center"><?php $this->show('Actions'); ?></th>
                </tr>
                
                <tr class="filter">
                    <th class="text-center">
                        <?php if (!empty($orders)):?>
                        <input type="checkbox" />
                        <?php endif; ?>
                    </th>
                    <th class="col-md-1"><?php echo Element::number('filter[id]', $filter->get('id'), array('class' => 'form-control', 'min' => '1')); ?></th>
                    <th class="col-md-2">
                        <?php echo Element::select('filter[order_status_id]', $orderStatuses, $filter->get('order_status_id'), array('class' => 'form-control'), null); ?>
                    </th>
                    <th><?php echo Element::text('filter[date]', $filter->get('date'), array('class' => 'form-control')); ?></th>
                    <th><?php echo Element::text('filter[name]', $filter->get('name'), array('class' => 'form-control')); ?></th>
                    <th><?php echo Element::text('filter[email]', $filter->get('email'), array('class' => 'form-control')); ?></th>
                    <th><?php echo Element::text('filter[phone]', $filter->get('phone'), array('class' => 'form-control')); ?></th>
                    <th><?php echo Element::text('filter[address]', $filter->get('address'), array('class' => 'form-control')); ?></th>
                    <th></th>
                    <th></th>
                    <th class="col-md-1"><?php echo Element::number('filter[qty]', $filter->get('qty'), array('class' => 'form-control', 'min' => '1')); ?></th>
                    <th><?php echo Element::number('filter[total_price]', $filter->get('total_price'), array('class' => 'form-control', 'step' => 'any', 'min' => '1')); ?></th>
                    <th></th>
                    <th><?php echo BooleanWidget::render(array('name' => 'filter[approved]', 'class' => 'form-control'), $filter->get('approved'), $this->getTranslator()); ?></th>
                    <th></th>
                </tr>
            </thead>
            
            <?php if (!empty($orders)): ?>
            <tbody>
                <?php foreach($orders as $order): ?>
                <tr <?php HtmlHelper::addClassOnDemand(!$order->getApproved(), 'warning'); ?>>
                    <td class="text-center">
                        <input type="checkbox" name="toDelete[<?php echo $order->getId(); ?>]" />
                    </td>
                    <td class="text-center text-muted"><?php echo $order->getId(); ?></td>
                    <td class="text-center text-muted">
                        <?php echo Element::select(sprintf('order_status_id[%s]', $order->getId()), $orderStatuses, $order->getStatusId(), array('class' => 'form-control'), null); ?>
                    </td>
                    <td class="text-center"><?php echo $order->getDate(); ?></td>
                    <td class="text-center"><?php echo $order->getName(); ?></td>
                    <td class="text-center"><?php echo $order->getEmail(); ?></td>
                    <td class="text-center"><?php echo $order->getPhone(); ?></td>
                    <td class="text-center"><?php echo $order->getAddress(); ?></td>
                    <td class="text-center"><?php echo $order->getComment(); ?></td>
                    <td class="text-center"><?php echo $order->getDelivery(); ?></td>
                    <td class="text-center"><?php echo $order->getQty(); ?></td>
                    <td class="text-center"><?php echo $order->getTotalPrice(), PHP_EOL, $config->getCurrency(); ?></td>
                    <td class="text-center"><?php echo $order->getDiscount(), PHP_EOL, $config->getCurrency(); ?></td>
                    <td class="text-center"><?php $this->show($order->getApproved() ? 'Yes' : 'No'); ?></td>
                    <td class="text-center">
                        <?php if (!$order->getApproved()):?>
                        <a data-toggle="tooltip" data-placement="left" title="<?php $this->show('Approve this order'); ?>" data-button="approve" data-url="<?php echo $this->url('Shop:Admin:Order@approveAction', $order->getId()); ?>" href="#"><i class="glyphicon glyphicon-ok"></i></a>
                        <?php endif; ?>
                        
                        <a data-toggle="tooltip" data-placement="left" title="<?php $this->show('Remove this order'); ?>" data-button="delete" data-url="<?php echo $this->url('Shop:Admin:Order@deleteAction', $order->getId()); ?>" href="#"><i class="glyphicon glyphicon-remove"></i></a>
                        <a data-toggle="tooltip" data-placement="left" title="<?php $this->show('View purchased products'); ?>" data-button="details" data-url="<?php echo $this->url('Shop:Admin:Order@detailsAction', $order->getId()); ?>" href="#"><i class="glyphicon glyphicon-th-list"></i></a>
                    </td>
                </tr>
                <?php endforeach; ?>
            </tbody>
            <?php endif; ?>
        </table>

        <?php if (empty($orders)): ?>
        <div class="center-block">
            <h2 class="text-center text-muted"><i class="glyphicon glyphicon-remove"></i> <?php $this->show('No orders'); ?></h2>
        </div>
        
        <?php else: ?>
        <?php if ($filter->isApplied()): ?>
        
        <div>
            <a href="<?php echo $this->url('Shop:Admin:Order@indexAction'); ?>" class="btn btn-primary"><i class="glyphicon glyphicon-trash"></i> <?php $this->show('Reset filter'); ?></a>
            <?php endif; ?>
            <button type="submit" class="btn btn-default"><i class="glyphicon glyphicon-filter"></i> <?php $this->show('Filter'); ?></button>
            <br />
        </div>
        <?php endif; ?>
    </form>
    
    <?php $this->loadPartial('paginator'); ?>
</div>

<div class="modal fade" id="details-modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
 <div class="modal-dialog modal-lg">
  <div class="modal-content">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
      <h4 class="modal-title"><i class="glyphicon glyphicon-eye-open"></i> <?php $this->show('Order details'); ?></h4>
    </div>
    <div class="modal-body" id="details-body"></div>
    <div class="modal-footer">
        <button type="button" class="btn btn-primary" data-dismiss="modal"><i class="glyphicon glyphicon-ok"></i> OK</button>
    </div>
 </div>
 </div>  
</div>
