<?php defined('KRYSTAL') or die; ?>
<?php

use Krystal\Form\Element;
use Krystal\Form\HtmlHelper;
use Shop\Service\AttributeProcessor;

?>

<?php if (!empty($categories)): ?>

<form data-group="product">
    
    <ul class="nav nav-tabs" role="tablist">
        <li role="presentation" class="active"><a href="#product" role="tab" data-toggle="tab"><i class="glyphicon glyphicon-shopping-cart"></i> <?php $this->show('Product'); ?></a></li>
        <li role="presentation"><a href="#configuration" role="tab" data-toggle="tab"><i class="glyphicon glyphicon-th-list"></i> <?php $this->show('Configuration'); ?></a></li>
        <li role="presentation"><a href="#images" role="tab" data-toggle="tab"><i class="glyphicon glyphicon-picture"></i> <?php $this->show('Images'); ?></a></li>
        <li role="presentation"><a href="#attrs" role="tab" data-toggle="tab"><i class="glyphicon glyphicon-th-list"></i> <?php $this->show('Attributes'); ?></a></li>
    </ul>
    
    <div class="tab-content">
        <!--Product tab-->
        <div role="tabpanel" class="tab-pane active" id="product">
            <div class="well">
                
                <?php echo Element::hidden('product[id]', $product->getId()); ?>
                <?php echo Element::hidden('product[cover]', $product->getCover()); ?>
                <?php echo Element::hidden('product[web_page_id]', $product->getWebPageId()); ?>
                
                <div class="form-group">
                    <label class="col-lg-2 control-label"><?php $this->show('Name'); ?></label>
                    <div class="col-lg-10">
                        <div class="input-group">
                            <?php echo Element::text('product[name]', $product->getName(), array('class' => 'form-control', 'data-input' => 'title', 'placeholder' => $this->translate('Product name'))); ?>
                            <span class="input-group-addon"><i class="glyphicon glyphicon-pencil"></i></span>
                        </div>
                    </div>
                </div>
                
                <div class="form-group">
                    <label class="col-lg-2 control-label"><?php $this->show('Price'); ?></label>
                    <div class="col-lg-10">
                        <div class="input-group">
                            <?php echo Element::number('product[regular_price]', $product->getPrice(), array('class' => 'form-control', 'min' => '1', 'step' => '0.01', 'placeholder' => $this->translate('Price of the product to be added'))); ?>
                            <span class="input-group-addon"><i class="glyphicon glyphicon-euro"></i></span>
                        </div>
                    </div>
                </div>
                
                <div class="form-group <?php echo !$config->getStokePriceEnabled() ? 'hidden' : ''; ?>">
                    <label class="col-lg-2 control-label"><?php $this->show('Stoke price'); ?></label>
                    <div class="col-lg-10">
                        <div class="input-group">
                            <?php echo Element::number('product[stoke_price]', $product->getStokePrice(), array('class' => 'form-control', 'placeholder' => $this->translate('Stoke price'))); ?>
                            <span class="input-group-addon"><i class="glyphicon glyphicon-euro"></i></span>
                        </div>
                    </div>
                </div>
                
                <div class="form-group">
                    <label class="col-lg-2 control-label"><?php $this->show('Category'); ?></label>
                    <div class="col-lg-10">
                        <?php echo Element::select('product[category_id][]', $categories, $product->getCategoryIds(), array('class' => 'form-control', 'multiple' => true, 'id' => 'categories')); ?>
                    </div>
                </div>

                <div class="form-group">
                    <label class="col-lg-2 control-label"><?php $this->show('Description'); ?></label>
                    <div class="col-lg-10">
                        <?php echo Element::textarea('product[description]', $product->getDescription(), array('data-wysiwyg' => 'true')); ?>
                    </div>
                </div>
                
                <div class="options">
                    <div class="form-group">
                        <label class="col-lg-2 control-label"><?php $this->show('Published'); ?></label>
                        <div class="col-lg-10">
                            <?php echo Element::checkbox('product[published]', $product->getPublished(), array('class' => 'form-control')); ?>
                        </div>
                    </div>
                    
                    <div class="form-group">
                        <label class="col-lg-2 control-label"><?php $this->show('Enable SEO'); ?></label>
                        <div class="col-lg-10">
                            <?php echo Element::checkbox('product[seo]', $product->getSeo(), array('class' => 'form-control')); ?>
                        </div>
                    </div>
                    
                    <div class="form-group">
                        <label class="col-lg-2 control-label"><?php $this->show('Slug'); ?></label>
                        <div class="col-lg-10">
                            <div class="input-group">
                                <?php echo Element::text('product[slug]', $product->getSlug(), array('class' => 'form-control', 'data-input' => 'slug', 'placeholder' => $this->translate('URL slug for this product. By default is taken from a title'))); ?>
                                <span class="input-group-addon">
                                    <a href="#" data-button="slug"><i class="glyphicon glyphicon-refresh" data-toggle="tooltip" title="<?php $this->show('Refresh the slug'); ?>"></i></a>
                                </span>
                            </div>
                        </div>
                    </div>
                    
                    <div class="form-group">
                        <label class="col-lg-2 control-label"><?php $this->show('Title'); ?></label>
                        <div class="col-lg-10">
                            <div class="input-group">
                                <?php echo Element::text('product[title]', $product->getTitle(), array('class' => 'form-control', 'data-input' => 'title', 'placeholder' => $this->translate('Product title'))); ?>
                                <span class="input-group-addon"><i class="glyphicon glyphicon-pencil"></i></span>
                            </div>
                        </div>
                    </div>
                    
                    <div class="form-group">
                        <label class="col-lg-2 control-label"><?php $this->show('Keywords'); ?></label>
                        <div class="col-lg-10">
                            <?php echo Element::textarea('product[keywords]', $product->getKeywords(), array('class' => 'form-control', 'placeholder' => $this->translate('Keywords used for search engines'))); ?>
                        </div>
                    </div>
                    
                    <div class="form-group">
                        <label class="col-lg-2 control-label"><?php $this->show('Description'); ?></label>
                        <div class="col-lg-10">
                            <?php echo Element::textarea('product[meta_description]', $product->getMetaDescription(), array('class' => 'form-control', 'placeholder' => $this->translate('Meta description for search engines'))); ?>
                        </div>
                    </div>
                </div>
            </div>

            <?php if (!$product->getId()): ?>

            <button data-button="add" data-back-url="<?php echo $this->url('Shop:Admin:Product@editAction', null); ?>" data-url="<?php echo $this->url('Shop:Admin:Product@saveAction'); ?>" class="btn btn-primary"><i class="glyphicon glyphicon-floppy-saved"></i> <?php $this->show('Add'); ?></button>
            <button data-button="add-create" data-url="<?php echo $this->url('Shop:Admin:Product@saveAction'); ?>" class="btn btn-primary"><i class="glyphicon glyphicon-floppy-save"></i> <?php $this->show('Add & Create new'); ?></button>

            <?php else: ?>

            <button data-button="save" data-url="<?php echo $this->url('Shop:Admin:Product@saveAction'); ?>" class="btn btn-primary"><i class="glyphicon glyphicon-floppy-saved"></i> <?php $this->show('Save'); ?></button>
            <button data-button="save-create" data-back-url="<?php echo $this->url('Shop:Admin:Product@addAction'); ?>" data-url="<?php echo $this->url('Shop:Admin:Product@saveAction'); ?>" class="btn btn-primary"><i class="glyphicon glyphicon-floppy-open"></i> <?php $this->show('Save & Create new'); ?></button>

            <?php endif; ?>

            <button data-button="options" class="btn btn-primary"><i class="glyphicon glyphicon-open"></i> <?php $this->show('More options'); ?></button>
            <button data-button="cancel" data-url="<?php echo $this->url('Shop:Admin:Browser@indexAction'); ?>" class="btn btn-default"><i class="glyphicon glyphicon-floppy-remove"></i> <?php $this->show('Cancel'); ?></button>
        </div>
        <!--/Home tab-->

      <!--Images tab-->
      <div role="tabpanel" class="tab-pane" id="configuration">
        <div class="well">
            <div class="form-group <?php HtmlHelper::addOnDemand($config->getSpecialSupport(), 'hidden'); ?>">
                <label class="col-lg-2 control-label"><?php $this->show('Special offer'); ?></label>
                <div class="col-lg-10">
                    <?php echo Element::checkbox('product[special_offer]', $product->getSpecialOffer(), array('class' => 'form-control')); ?>
                </div>
            </div>
            
            <div class="form-group">
                <label class="col-lg-2 control-label"><?php $this->show('Order'); ?></label>
                <div class="col-lg-10">
                    <div class="input-group">
                        <?php echo Element::number('product[order]', $product->getOrder(), array('class' => 'form-control', 'placeholder' => $this->translate('Product sorting order'))); ?>
                        <span class="input-group-addon"><i class="glyphicon glyphicon-pencil"></i></span>
                    </div>
                </div>
            </div>

            <div class="form-group">
                <label class="col-lg-2 control-label"><?php $this->show('In stock'); ?></label>
                <div class="col-lg-10">
                    <div class="input-group">
                        <?php echo Element::number('product[in_stock]', $product->getInStock(), array('class' => 'form-control', 'placeholder' => $this->translate('Quantity of this product in stock'))); ?>
                        <span class="input-group-addon"><i class="glyphicon glyphicon-pencil"></i></span>
                    </div>
                </div>
            </div>
            
            <div class="form-group">
                <label class="col-lg-2 control-label"><?php $this->show('Recommended products'); ?></label>
                <div class="col-lg-10">
                    <?php echo Element::select('product[recommended_ids][]', $names, $product->getRecommendedIds(), array('class' => 'form-control', 'multiple' => true)); ?>
                </div>
            </div>

            <div class="form-group">
                <label class="col-lg-2 control-label"><?php $this->show('Similar products'); ?></label>
                <div class="col-lg-10">
                    <?php echo Element::select('product[similar_ids][]', $names, $product->getSimilarIds(), array('class' => 'form-control', 'multiple' => true)); ?>
                </div>
            </div>
        </div>
      </div>
        
      <!--Images tab-->
      <div role="tabpanel" class="tab-pane" id="images">
        <div class="well">
            
            <div id="file-input-container">
                <?php echo Element::file('file[]', 'image/x-png, image/gif, image/jpeg'); ?>
            </div>
            
            <div class="btn-container">
                <a class="btn btn-default dropdown-toggle" data-button="upload" href="#"><i class="glyphicon glyphicon-camera"></i> <?php $this->show('Upload new image'); ?></a></a>
            </div>
            
            <div class="table-responsive">
                <table class="table table-hover table-striped table-bordered table-condensed">
                    <thead>
                        <tr>
                            <th class="text-center"><?php $this->show('Image'); ?></th>
                            <th class="text-center"><?php $this->show('Order'); ?></th>
                            <th class="text-center"><?php $this->show('Published'); ?></th>
                            <th class="text-center"><?php $this->show('Cover'); ?></th>
                            <th class="text-center"><?php $this->show('Actions'); ?></th>
                        </tr>
                    </thead>
                    
                    <tbody data-container="image">
                        
                        <?php if (!empty($photos)): ?>
                        <?php foreach ($photos as $photo): ?>
                        
                        <tr>
                            <td>
                                <img class="img-responsive center-block" data-image="" width="200" height="200" src="<?php echo $photo->getImageBag()->getUrl('200x200'); ?>" />
                            </td>
                            
                            <td class="text-center col-md-1">
                                <?php echo Element::number(sprintf('photos[order][%s]', $photo->getId()), $photo->getOrder(), array('class' => 'form-control center-block', 'min' => '0')); ?>
                            </td>
                            
                            <td class="text-center">
                                <?php echo Element::checkbox(sprintf('photos[published][%s]', $photo->getId()), $photo->getPublished()); ?>
                            </td>
                            
                            <td class="text-center">
                                <?php echo Element::radio('photos[cover]', $photo->getImage(), $product->getCover() == $photo->getImage()); ?>
                            </td>
                            
                            <td class="text-center">
                                <a data-toggle="tooltip" data-placement="left" data-original-title="<?php $this->show('Replace this image'); ?>" data-button="edit" data-image="<?php echo $photo->getImage(); ?>" href="#"><i class="glyphicon glyphicon-pencil"></i></a>
                                
                                <?php if ($product->getCover() != $photo->getImage()): ?>
                                <?php echo Element::checkbox(sprintf('photos[toDelete][%s]', $photo->getId()), false, array('data-toggle' => 'tooltip', 'data-placement' => 'left', 'data-original-title' => $this->translate('Check if you want to remove this image')), false); ?> <span class="product-remove-caption"><?php $this->show('Remove'); ?></span>
                                <?php endif; ?>
                                
                                <?php echo Element::file(sprintf('image_%s', $photo->getId()), 'image/x-png, image/gif, image/jpeg', array('class' => 'hidden')); ?>
                            </td>
                        </tr>
                        
                        <?php endforeach; ?>
                        <?php endif; ?>
                        
                    </tbody>
                </table>
            </div>
        </div>
      </div>
      
      <div role="tabpanel" class="tab-pane" id="attrs">
        <div class="well">
            <?php foreach ($attributes as $attribute): ?>
            
            <div class="form-group">
                <label class="col-lg-2 control-label"><?php echo $attribute['group_name']; ?></label>
                <div class="col-lg-10">
                    <?php echo Element::select(
                        sprintf('product[attributes][%s]', $attribute['group_id']), 
                        $attribute['attributes'], 
                        AttributeProcessor::findActiveAttribute($attribute['attributes'], $attributes, $activeAttributes),
                        array('class' => 'form-control', 'multiple' => $attribute['group_dynamic'])
                    ); ?>
                </div>
            </div>
            <?php endforeach; ?>
        </div>
      </div>

      <!--Images tab-->
    </div>
</form>

<?php else: ?>

<div class="well">
    <div class="center-block">
        <h2 class="text-muted text-center"><i class="glyphicon glyphicon-remove"></i> <?php $this->show('Before you add a product, you need to create at least one category'); ?></h2>
    </div>
</div>

<?php endif; ?>
