<?php defined('KRYSTAL') or die; ?>

<p><?= $this->translate('Hello there!'); ?></p>
<p><?= $this->translate('You have a new order from'); ?>: <?= $input['name']; ?></p>
<p><?= $this->translate('Contact information'); ?>:</p>
<p><?= $this->translate('Phone'); ?>: <?= $input['phone']; ?></p>
<p><?= $this->translate('Email'); ?>: <?= $input['email']; ?></p>
<p><?= $this->translate('Address'); ?>: <?= $input['address']; ?></p>
<p><?= $this->translate('Delivery type'); ?>: <?= $input['delivery']; ?></p>

<?php if (!empty($input['comment'])): ?>
<p><?= $this->translate('Comments'); ?>:</p>
<?= $input['comment']; ?>
<?php endif; ?>

<br />

<p><?= $this->translate('Ordered products'); ?>: </p>

<?php foreach ($basketManager->getProducts() as $product): ?>
<br />
<p><?= $this->translate('Product'); ?>: <?= $product->getName(); ?></p>
<p><?= $this->translate('Quantity'); ?> : <?= $product->getQty(); ?></p>
<p><?= $this->translate('Sub-total price'); ?>: <?= $product->getSubTotalPrice(), ' ', $currency; ?></p>
<br />
<?php endforeach; ?>

<br />
<hr />

<?php if (!empty($input['discount'])): ?>
<p><?= $this->translate('Discount'); ?>: <?= $input['discount']; ?></p>
<?php endif; ?>

<p><?= $this->translate('Total quantity of all products'); ?>: <?= $basketManager->getTotalQuantity(); ?></p>
<p><?= $this->translate('Total price'); ?>: <?= $basketManager->getTotalPrice(), ' ', $currency; ?></p>
