<?php

use Krystal\Form\Element;
defined('KRYSTAL') or die;

?>

<form data-group="brand">
	<div class="well">
        <?= Element::hidden('brand[id]', $brand->getId()); ?>

		<div class="form-group">
			<label class="col-lg-2 control-label"><?php $this->show('Name'); ?></label>
			<div class="col-lg-10">
				<div class="input-group">
					<?php echo Element::text('brand[name]', $brand->getName(), array('class' => 'form-control', 'placeholder' => $this->translate('Name'))); ?>
					<span class="input-group-addon"><i class="glyphicon glyphicon-pencil"></i></span>
				</div>
			</div>
        </div>

        <div class="form-group">
			<label class="col-lg-2 control-label"><?php $this->show('Order'); ?></label>
			<div class="col-lg-10">
				<div class="input-group">
					<?php echo Element::text('brand[order]', $brand->getORder(), array('class' => 'form-control', 'placeholder' => $this->translate('Sorting order'))); ?>
					<span class="input-group-addon"><i class="glyphicon glyphicon-pencil"></i></span>
				</div>
			</div>
        </div>
	</div>

    <?php if ($new): ?>
	<button data-button="add" data-back-url="<?php echo $this->url('Shop:Admin:Brand@editAction', null); ?>" data-url="<?php echo $this->url('Shop:Admin:Brand@saveAction'); ?>" class="btn btn-primary"><i class="glyphicon glyphicon-floppy-save"></i> <?php $this->show('Add'); ?></button>
	<button data-button="add-create" data-url="<?php echo $this->url('Shop:Admin:Brand@saveAction'); ?>" class="btn btn-primary"><i class="glyphicon glyphicon-floppy-save"></i> <?php $this->show('Add & Create new'); ?></button>
	<?php else: ?>

	<button data-button="save" data-url="<?php echo $this->url('Shop:Admin:Brand@saveAction'); ?>" class="btn btn-primary"><i class="glyphicon glyphicon-floppy-save"></i> <?php $this->show('Save'); ?></button>
	<button data-button="save-create" data-back-url="<?php echo $this->url('Shop:Admin:Brand@addAction'); ?>" data-url="<?php echo $this->url('Shop:Admin:Brand@saveAction'); ?>" class="btn btn-primary"><i class="glyphicon glyphicon-floppy-save"></i> <?php $this->show('Save & Create new'); ?></button>

	<?php endif; ?>
    <button data-button="cancel" data-url="<?php echo $this->url('Shop:Admin:Browser@indexAction'); ?>" class="btn btn-default"><i class="glyphicon glyphicon-floppy-remove"></i> <?php $this->show('Cancel'); ?></button>
</form>