<?php

use Krystal\Form\Element;
use Krystal\Widget\GridView\GridViewWidget;
use Cms\View\Icon;

defined('KRYSTAL') or die;

?>

<div class="btn-toolbar mb-3">
    <div class="dropdown">
        <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown">
            <i class="bi bi-list"></i> <?= $this->translate('Menu'); ?>
        </button>

        <div class="dropdown-menu">
            <a class="dropdown-item" href="<?= $this->url('Shop:Admin:SpecificationCategory@addAction'); ?>">
                <i class="bi bi-folder-plus"></i> <?= $this->translate('Add category'); ?>
            </a>
            <a class="dropdown-item" href="<?= $this->url('Shop:Admin:SpecificationItem@addAction'); ?>">
                <i class="bi bi-box-seam"></i> <?= $this->translate('Add new item'); ?>
            </a>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-lg-6">
        <div class="card shadow-sm">
            <div class="card-header">
                <h3 class="card-title m-0">
                    <i class="bi bi-pencil-square"></i> <?= $this->translate('Specifications'); ?> 
                    <small class="text-muted">(<?= count($items); ?>)</small>
                </h3>
            </div>
            
            <div class="card-body p-0">
                <div class="table-responsive">
                    <?= $this->widget(new GridViewWidget($items, [
                        'tableClass' => 'table table-hover table-bordered table-striped m-0',
                        'columns' => [
                            [
                                'column' => 'id',
                                'label' => '#'
                            ],
                            [
                                'column' => 'name',
                            ],
                            [
                                'column' => 'front',
                                'translateable' => true,
                                'value' => function($row){
                                    return $row['front'] ? 'Yes' : 'No';
                                }
                            ],
                        ],
                        'actions' => [
                            function($row){
                                return Icon::edit(
                                    $this->url('Shop:Admin:SpecificationItem@editAction', $row['id']),
                                    $this->translate('Edit this item')
                                );
                            },
                            function($row){
                                return Icon::remove(
                                    $this->url('Shop:Admin:SpecificationItem@deleteAction', $row['id']),
                                    $this->translate('Remove this item')
                                );
                            }
                        ]
                    ])); ?>
                </div>

                <?php if (empty($items)): ?>
                <div class="text-center py-5">
                    <h2 class="text-muted"><i class="bi bi-x-circle"></i> <?= $this->translate('No items'); ?></h2>
                </div>
                <?php endif; ?>
            </div>
        </div>
    </div>

    <div class="col-lg-6">
        <div class="card shadow-sm">
            <div class="card-header">
                <h3 class="card-title m-0">
                    <i class="bi bi-folder"></i> <?= $this->translate('Categories'); ?> 
                    <small class="text-muted">(<?= count($categories); ?>)</small>
                </h3>
            </div>

            <div class="card-body p-0">
                <div class="table-responsive">
                    <?= $this->widget(new GridViewWidget($categories, [
                        'tableClass' => 'table table-hover table-bordered table-striped m-0',
                        'rowAttributes' => [
                            'class' => function($row) use ($categoryId){
                                return $row['id'] == $categoryId ? 'table-info' : null;
                            }
                        ],
                        'columns' => [
                            [
                                'column' => 'id',
                                'label' => '#'
                            ],
                            [
                                'column' => 'name',
                                'value' => function($entity){
                                    return Element::link($entity['name'], $this->url('Shop:Admin:SpecificationItem@indexAction', $entity['id']));
                                }
                            ],
                            [
                                'column' => 'order',
                            ],
                            [
                                'column' => 'item_count',
                                'label' => 'Item count'
                            ],
                        ],
                        'actions' => [
                            function($row){
                                return Icon::edit(
                                    $this->url('Shop:Admin:SpecificationCategory@editAction', $row['id']), 
                                    $this->translate('Edit this category')
                                );
                            },

                            function($row){
                                return Icon::remove(
                                    $this->url('Shop:Admin:SpecificationCategory@deleteAction', $row['id']),
                                    $this->translate('Remove this category')
                                );
                            }
                        ]
                    ])); ?>
                </div>

                <?php if (empty($categories)): ?>
                <div class="text-center py-5">
                    <h2 class="text-muted"><i class="bi bi-x-circle"></i> <?= $this->translate('No categories'); ?></h2>
                </div>
                <?php endif; ?>
            </div>
        </div>
    </div>
</div>