<?php

defined('KRYSTAL') or die;

?>

<h2 class="page-header"><i class="glyphicon glyphicon-list-alt"></i> <?php $this->show('Available order statuses'); ?> <small>(<?php echo count($orderStatuses); ?>)</small></h2>

<div class="table-responsive">
    <table class="table table-stripped table-bordered table-hover">
        <thead>
            <tr>
                <td class="text-center text-muted">#</td>
                <td class="text-center"><?php $this->show('Name'); ?></td>
                <td class="text-center"><?php $this->show('Description'); ?></td>
                <td class="text-center"><?php $this->show('Actions'); ?></td>
            </tr>
        </thead>

        <tbody>
            <?php foreach ($orderStatuses as $entity): ?>
            <tr>
                <td class="text-center text-muted"><?php echo $entity->getId(); ?></td>
                <td class="text-center"><?php echo $entity->getName(); ?></td>
                <td class="text-center"><?php echo $entity->getDescription(); ?></td>
                <td class="text-center">
                    <a data-button="edit" data-toggle="tooltip" data-placement="left" data-original-title="<?php $this->show('Edit this order status'); ?>" href="<?php echo $this->url('Shop:Admin:OrderStatus@editAction', $entity->getId()); ?>"><i class="glyphicon glyphicon-pencil"></i></a>
                    <a data-button="delete" data-back-url="<?php echo $this->url('Shop:Admin:OrderStatus@indexAction'); ?>" data-url="<?php echo $this->url('Shop:Admin:OrderStatus@deleteAction', $entity->getId()); ?>" data-toggle="tooltip" data-placement="left" data-original-title="<?php $this->show('Remove this order status'); ?>" href="#"><i class="glyphicon glyphicon-remove"></i></a>
                </td>
            </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
</div>

<?php if (empty($orderStatuses)): ?>
<div class="center-block">
    <h2 class="text-center text-muted"><i class="glyphicon glyphicon-remove"></i> <?php $this->show('No order statuses'); ?></h2>
</div>
<?php endif; ?>
