<?php

use Krystal\Grid\Grid;
use Krystal\Form\Element;
use Cms\View\Icon;

defined('KRYSTAL') or die;

?>

<h2 class="page-header"><i class="glyphicon glyphicon-list-alt"></i> <?php $this->show('Available order statuses'); ?> <small>(<?php echo count($orderStatuses); ?>)</small></h2>

<div class="table-responsive">
    <?= Grid::render($orderStatuses, array(
        'tableClass' => 'table table-hover table-bordered table-striped table-condensed',
        'columns' => array(
            array(
                'column' => 'id',
                'label' => '#'
            ),

            array(
                'column' => 'name',
            ),

            array(
                'column' => 'description'
            )
        ),

        'actions' => array(
            'edit' => function($row){
                return Icon::edit(
                    $this->url('Shop:Admin:OrderStatus@editAction', $row['id']),
                    $this->translate('Edit this order status')
                );
            },

            'remove' => function($row){
                return Icon::remove(
                    $this->url('Shop:Admin:OrderStatus@deleteAction', $row['id']),
                    $this->translate('Remove this order status'),
                    null,
                    $this->url('Shop:Admin:OrderStatus@indexAction')
                );
            }
        )

    ), $this->translator); ?>
</div>

<?php if (empty($orderStatuses)): ?>
<div class="center-block">
    <h2 class="text-center text-muted"><i class="glyphicon glyphicon-remove"></i> <?php $this->show('No order statuses'); ?></h2>
</div>
<?php endif; ?>
