<?php

use Krystal\Form\Element;
use Krystal\Widget\GridView\GridViewWidget;
use Cms\View\Icon;

defined('KRYSTAL') or die;

?>

<div class="btn-toolbar mb-3">
    <div class="btn-group mr-2">
        <a class="btn btn-sm btn-primary" href="<?= $this->url('Shop:Admin:AttributeValue@addAction'); ?>">
            <i class="bi bi-tag"></i> <?= $this->translate('Add attribute'); ?>
        </a>
    </div>

    <div class="btn-group">
        <a class="btn btn-sm btn-primary" href="<?= $this->url('Shop:Admin:AttributeGroup@addAction'); ?>">
            <i class="bi bi-collection"></i> <?= $this->translate('Add group'); ?>
        </a>
    </div>
</div>

<div class="row">
    <div class="col-lg-6">
        <div class="card p-3">
            <h4 class="card-title">
                <i class="bi bi-tags"></i> <?= $this->translate('Values'); ?> 
                <small class="text-muted">(<?= count($values); ?>)</small>
            </h4>

            <?= $this->widget(new GridViewWidget($values, [
                'tableClass' => 'table table-hover table-bordered table-striped',
                'columns' => [
                    [
                        'column' => 'id',
                        'label' => '#'
                    ],
                    [
                        'column' => 'name'
                    ]
                ],
                'actions' => [
                    function($value) {
                        return Icon::edit(
                            $this->url('Shop:Admin:AttributeValue@editAction', $value->getId()),
                            $this->translate('Edit this attribute')
                        );
                    },

                    function($value) {
                        return Icon::remove(
                            $this->url('Shop:Admin:AttributeValue@deleteAction', $value->getId()),
                            $this->translate('Remove this attribute')
                        );
                    }
                ]
            ])); ?>
        </div>
    </div>

    <div class="col-lg-6">
        <div class="card p-3">
            <h4 class="card-title">
                <i class="bi bi-collection-play"></i> <?= $this->translate('Groups'); ?> 
                <small class="text-muted">(<?= count($groups); ?>)</small>
            </h4>

            <?= $this->widget(new GridViewWidget($groups, [
                'tableClass' => 'table table-hover table-bordered table-striped',
                'rowAttributes' => [
                    'class' => function($group) use ($groupId) {
                        return $groupId == $group->getId() ? 'table-info' : null;
                    }
                ],
                'columns' => [
                    [
                        'column' => 'id',
                        'label' => '#'
                    ],
                    [
                        'column' => 'name',
                        'value' => function($group) {
                            return Element::link($group->getName(), $this->url('Shop:Admin:Attributes@groupAction', $group->getId()));
                        }
                    ],
                    [
                        'column' => 'dynamic',
                        'translateable' => true,
                        'value' => function($group) {
                            return $group->getDynamic() ? 'Yes' : 'No';
                        }
                    ]
                ],

                'actions' => [
                    function($group) {
                        return Icon::edit(
                            $this->url('Shop:Admin:AttributeGroup@editAction', $group->getId()),
                            $this->translate('Edit this group')
                        );
                    },

                    function($group) {
                        return Icon::remove(
                            $this->url('Shop:Admin:AttributeGroup@deleteAction', $group->getId()),
                            $this->translate('Remove this group')
                        );
                    }
                ]
            ])); ?>
        </div>
    </div>
</div>