<?php

use Krystal\Form\Element;
use Cms\Service\LanguageManager;
defined('KRYSTAL') or die;

?>

<h3 class="page-header"><i class="glyphicon glyphicon-pencil"></i> <?php $this->show($this->getBreadcrumbBag()->getLastName()); ?></h3>

<form data-group="value" autocomplete="off">
    <ul class="nav nav-tabs" role="tablist">
        <li role="presentation" class="active"><a href="#category" role="tab" data-toggle="tab"><i class="glyphicon glyphicon-file"></i> <?php $this->show('Value'); ?></a></li>
        <li role="presentation"><a href="#settings" role="tab" data-toggle="tab"><i class="glyphicon glyphicon-file"></i> <?php $this->show('Settings'); ?></a></li>
	</ul>

    <div class="tab-content">
        <div class="tab-pane fade in active" id="category" role="tabpanel">
            <div class="well">
                <?php $this->loadPartial('language-tabs'); ?>

                <div class="tab-content">
                    <?php foreach ($languages as $index => $language): ?>
                    <div class="tab-pane fade in <?php echo $index == 0 ? 'active' : null; ?>" id="<?php printf('language-%s', $language->getId()); ?>" role="tabpanel">
                        <?php $entity = LanguageManager::findByLangId($language->getId(), $value); ?>

                        <?php echo Element::hidden(sprintf('translation[%s][id]', $language->getId()), $entity->getId()); ?>
                        <?php echo Element::hidden(sprintf('translation[%s][lang_id]', $language->getId()), $language->getId()); ?>
                        <?php $this->loadPartial('language-name', array('language' => $language)); ?>

                        <div class="form-group">
                            <label class="col-lg-2 control-label"><?php $this->show('Name'); ?></label>
                            <div class="col-lg-10">
                                <div class="input-group">
                                    <?php echo Element::text(sprintf('translation[%s][name]', $language->getId()), $entity->getName(), array('class' => 'form-control', 'placeholder' => $this->translate('Name'))); ?>
                                    <span class="input-group-addon"><i class="glyphicon glyphicon-pencil"></i></span>
                                </div>
                            </div>
                        </div>
                    </div>
                    <?php endforeach; ?>
                </div>
            </div>
        </div>

        <div class="tab-pane fade in" id="settings" role="tabpanel">
            <?php echo Element::hidden('value[id]', $entity->getId()); ?>

            <div class="well">
                <div class="form-group">
                    <label class="col-lg-2 control-label"><?php $this->show('Group'); ?></label>
                    <div class="col-lg-10">
                        <?php echo Element::select('value[group_id]', $groups, $entity->getGroupId(), array('class' => 'form-control')); ?>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <?php $this->loadPartial('actions', array(
        'new' => $new,
        'add' => 'Shop:Admin:AttributeValue@addAction',
        'edit' => 'Shop:Admin:AttributeValue@editAction',
        'save' => 'Shop:Admin:AttributeValue@saveAction',
        'cancel' => 'Shop:Admin:Browser@indexAction'
    )); ?>

</form>
