<?php

use Krystal\Form\Element;
defined('KRYSTAL') or die;

?>

<h3 class="page-header"><i class="glyphicon glyphicon-pencil"></i> <?php $this->show($deliveryType->getId() ? 'Update delivery type' : 'Add new delivery type'); ?></h3>

<form data-group="deliveryType">
    <div class="well">
        <input type="hidden" name="deliveryType[id]" value="<?php echo $deliveryType->getId(); ?>" />

        <div class="form-group">
            <label class="col-lg-2 control-label"><?php $this->show('Name'); ?></label>
            <div class="col-lg-10">
                <div class="input-group">
                    <?php echo Element::text('deliveryType[name]', $deliveryType->getName(), array('class' => 'form-control', 'placeholder' => $this->translate('Name'))); ?>
                    <span class="input-group-addon"><i class="glyphicon glyphicon-pencil"></i></span>
                </div>
            </div>
        </div>

        <div class="form-group">
            <label class="col-lg-2 control-label"><?php $this->show('Price'); ?></label>
            <div class="col-lg-10">
                <div class="input-group">
                    <?php echo Element::text('deliveryType[price]', $deliveryType->getPrice(), array('class' => 'form-control', 'placeholder' => $this->translate('Price'))); ?>
                    <span class="input-group-addon"><i class="glyphicon glyphicon-pencil"></i></span>
                </div>
            </div>
        </div>
    </div>

    <?php if (!$deliveryType->getId()): ?>

    <button data-button="add" data-back-url="<?php echo $this->url('Shop:Admin:DeliveryType@editAction', null); ?>" data-url="<?php echo $this->url('Shop:Admin:DeliveryType@saveAction'); ?>" class="btn btn-primary"><i class="glyphicon glyphicon-floppy-save"></i> <?php $this->show('Add'); ?></button>
    <button data-button="add-create" data-url="<?php echo $this->url('Shop:Admin:DeliveryType@saveAction'); ?>" class="btn btn-primary"><i class="glyphicon glyphicon-floppy-save"></i> <?php $this->show('Add & Create new'); ?></button>

    <?php else: ?>

    <button data-button="save" data-url="<?php echo $this->url('Shop:Admin:DeliveryType@saveAction'); ?>" class="btn btn-primary"><i class="glyphicon glyphicon-floppy-save"></i> <?php $this->show('Save'); ?></button>
    <button data-button="save-create" data-back-url="<?php echo $this->url('Shop:Admin:DeliveryType@indexAction'); ?>" data-url="<?php echo $this->url('Shop:Admin:DeliveryType@saveAction'); ?>" class="btn btn-primary"><i class="glyphicon glyphicon-floppy-save"></i> <?php $this->show('Save & Create new'); ?></button>
    <button data-button="cancel" data-url="<?php echo $this->url('Shop:Admin:DeliveryType@indexAction'); ?>" class="btn btn-default"><i class="glyphicon glyphicon-floppy-remove"></i> <?php $this->show('Cancel'); ?></button>

    <?php endif; ?>
</form>
