<?php

use Krystal\Form\Element;
use Cms\Service\LanguageManager;

defined('KRYSTAL') or die;

?>

<form class="card" data-group="deliveryType" autocomplete="off">
    <div class="card-header">
        <ul class="nav nav-tabs card-header-tabs" role="tablist">
            <li class="nav-item" role="presentation">
                <a class="nav-link active" href="#category" role="tab" data-toggle="tab">
                    <i class="bi bi-truck"></i> <?= $this->translate('Delivery type'); ?>
                </a>
            </li>
            <li class="nav-item" role="presentation">
                <a class="nav-link" href="#settings" role="tab" data-toggle="tab">
                    <i class="bi bi-gear"></i> <?= $this->translate('Settings'); ?>
                </a>
            </li>
        </ul>
    </div>

    <div class="card-body">
        <div class="tab-content">
            <div class="tab-pane fade show active" id="category" role="tabpanel">
                <?php $this->loadPartial('language-tabs'); ?>

                <div class="tab-content mt-3">
                    <?php foreach ($languages as $index => $language): ?>
                    <div class="tab-pane fade show <?= $index == 0 ? 'active' : null; ?>" id="<?= sprintf('language-%s', $language->getId()); ?>" role="tabpanel">
                        <?php $entity = LanguageManager::findByLangId($language->getId(), $deliveryType); ?>

                        <?= Element::hidden(sprintf('translation[%s][id]', $language->getId()), $entity->getId()); ?>
                        <?= Element::hidden(sprintf('translation[%s][lang_id]', $language->getId()), $language->getId()); ?>
                        
                        <?php $this->loadPartial('language-name', ['language' => $language]); ?>

                        <div class="form-group mb-3">
                            <label class="form-label"><?= $this->translate('Name'); ?></label>
                            <div class="input-group">
                                <?= Element::text(sprintf('translation[%s][name]', $language->getId()), $entity->getName(), ['class' => 'form-control', 'placeholder' => $this->translate('Name')]); ?>
                                <div class="input-group-append">
                                    <span class="input-group-text"><i class="bi bi-pencil"></i></span>
                                </div>
                            </div>
                        </div>
                    </div>
                    <?php endforeach; ?>
                </div>
            </div>

            <div class="tab-pane fade" id="settings" role="tabpanel">
                <?= Element::hidden('deliveryType[id]', $entity->getId()); ?>

                <div class="form-group mb-3">
                    <label class="form-label"><?= $this->translate('Price'); ?></label>
                    <div class="input-group">
                        <?= Element::text('deliveryType[price]', $entity->getPrice(), ['class' => 'form-control', 'placeholder' => $this->translate('Price')]); ?>
                        <div class="input-group-append">
                            <span class="input-group-text"><i class="bi bi-pencil"></i></span>
                        </div>
                    </div>
                </div>

                <div class="form-group mb-3">
                    <label class="form-label"><?= $this->translate('Order'); ?></label>
                    <div class="input-group">
                        <?= Element::text('deliveryType[order]', $entity->getOrder(), ['class' => 'form-control', 'placeholder' => $this->translate('Sorting order')]); ?>
                        <div class="input-group-append">
                            <span class="input-group-text"><i class="bi bi-pencil"></i></span>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="mt-3">
            <?php $this->loadPartial('actions', [
                'new' => $new,
                'add' => 'Shop:Admin:DeliveryType@addAction',
                'edit' => 'Shop:Admin:DeliveryType@editAction',
                'save' => 'Shop:Admin:DeliveryType@saveAction',
                'cancel' => 'Shop:Admin:DeliveryType@indexAction'
            ]); ?>
        </div>
    </div>
</form>