<?php

use Krystal\Form\Element;
use Krystal\Widget\GridView\GridViewWidget;
use Cms\View\Icon;

defined('KRYSTAL') or die;

?>

<div class="card">
    <div class="card-header d-flex justify-content-between align-items-center">
        <h3 class="card-title m-0">
            <i class="bi bi-truck"></i> <?= $this->translate('Available delivery types'); ?> 
            <small class="text-muted">(<?= count($deliveryTypes); ?>)</small>
        </h3>

        <a class="btn btn-primary btn-sm" href="<?= $this->url('Shop:Admin:DeliveryType@addAction'); ?>">
            <i class="bi bi-plus-lg"></i> <?= $this->translate('Add new delivery type'); ?>
        </a>
    </div>

    <div class="card-body table-responsive">
        <?= $this->widget(new GridViewWidget($deliveryTypes, [
            'tableClass' => 'table table-hover table-bordered table-striped',
            'columns' => [
                [
                    'column' => 'id',
                    'label' => '#'
                ],
                [
                    'column' => 'name',
                ],
                [
                    'column' => 'price'
                ],
                [
                    'column' => 'order'
                ]
            ],

            'actions' => [
                function($row){
                    return Icon::edit(
                        $this->url('Shop:Admin:DeliveryType@editAction', $row['id']),
                        $this->translate('Edit this delivery method')
                    );
                },

                function($row){
                    return Icon::remove(
                        $this->url('Shop:Admin:DeliveryType@deleteAction', $row['id']),
                        $this->translate('Remove this delivery type')
                    );
                }
            ]
        ])); ?>
    </div>
</div>