<?php

use Krystal\Form\Element;
use Krystal\Widget\GridWidget;
use Cms\View\Icon;

defined('KRYSTAL') or die;

?>

<h2 class="page-header"><i class="glyphicon glyphicon-list-alt"></i> <?php $this->show('Available delivery types'); ?> <small>(<?= count($deliveryTypes); ?>)</small></h2>

<p>
    <a class="btn btn-primary" href="<?= $this->url('Shop:Admin:DeliveryType@addAction'); ?>"><?php $this->show('Add new delivery type'); ?></a>
</p>

<div class="table-responsive">
    <?= $this->widget(new GridWidget($deliveryTypes, array(
        'tableClass' => 'table table-hover table-bordered table-striped table-condensed',
        'columns' => array(
            array(
                'column' => 'id',
                'label' => '#'
            ),

            array(
                'column' => 'name',
            ),

            array(
                'column' => 'price'
            ),

            array(
                'column' => 'order'
            )
        ),

        'actions' => array(
            'edit' => function($row){
                return Icon::edit(
                    $this->url('Shop:Admin:DeliveryType@editAction', $row['id']),
                    $this->translate('Edit this delivery method')
                );
            },

            'remove' => function($row){
                return Icon::remove(
                    $this->url('Shop:Admin:DeliveryType@deleteAction', $row['id']),
                    $this->translate('Remove this delivery type')
                );
            }
        )
    ))); ?>
</div>
